### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by mxplusb** [wtfutil/wtf#103]
Great project! I'm a Windows guy, so naturally I tried it on Windows in PowerShell. Works for me with `go build -v -o wtf.exe` or `go install -v` since I didn't have `make` installed.

There are some areas that do need fixing, but I wanted to start a top level issue with some of what I see out of the box with a vanilla config:

- [] Bad Character Encoding in the box headers.
- [] Linux-specific tools used.
- [] `Makefile` only works on Linux.

![image](https://user-images.githubusercontent.com/7537841/40811904-7594dd1a-64f0-11e8-9036-cef2404d9403.png)

You can see some of the issues in the screenshot. If you can point me to where that code exists, I might be able to help make it work as intended on Windows.

**Comment by senorprogrammer** [comment]
For the title characters, those are all hard-coded into the widgets themselves as unicode characters (i.e.: https://github.com/senorprogrammer/wtf/blob/bbdc860625ed45001bdc8bd737eb3643a5baba33/bamboohr/widget.go#L19). 

`Security` is entirely macOS-specific, however extracting that into platform-specific code shouldn't be too tough. Same with the build settings. 

`OS` and `Build` are macOS-specific, in the `System` module, a file called `system_info.go`. Rename that to `macos.go`, add a Windows-specific version, and branch in `widget.go` here https://github.com/senorprogrammer/wtf/blob/bbdc860625ed45001bdc8bd737eb3643a5baba33/system/widget.go#L30 and that shouldn't be too tough to get working either.

**Comment by mxplusb** [comment]
Gotcha, I will see how it goes, thanks!

**Comment by Thorocaine** [comment]
@mxplusb is it possible to distribute a Windows binary if you have already built it, or would it need to built per machine?

**Comment by mxplusb** [comment]
@Thorocaine depends on the license @senorprogrammer has, but once it's built, I'm sure it can get distributed by someone. :)

**Comment by senorprogrammer** [comment]
If the MIT license doesn't support that (and I'm pretty sure it does), then I'll switch to a license that does. You should be able to distribute whatever you build.

**Comment by Thorocaine** [comment]
I did manage to get it working (mostly) in Windows Subsystem for Linux.
The only thing that I have tried that doesn't show anything is the Calendar.

**Comment by mxplusb** [comment]
@Thorocaine `go build -v -o wtf.exe` works, there are just some weird nuances. If you are curious what support looks like, just take a look at #150.

**Comment by BattleBas** [comment]
Is there an update on distributing Windows binaries? There isn't a Windows binary included in the current release. Are there maybe still activate tickets waiting for completion before distribution is possible?
Thanks!

**Comment by senorprogrammer** [comment]
I just added a Windows target to the `.goreleaser` config. Next release we'll see what happens. I'll update here when that's done.

**Comment by mxplusb** [comment]
@senorprogrammer there are some changes coming in 1905 that implement much better Terminal support and might make it a bit more feasible  to do natively.

**Comment by senorprogrammer** [comment]
What does 1905 refer to?

**Comment by mxplusb** [comment]
1905 is the next release of Windows, comes out in May, it was delayed from March and was supposed to be 1903. Windows 10 is now released as Windows <2-digit year><2-digit month>, so 1809 is September 2018, 1903 is March 2019, 1905 would be May 2019. Very similar to the way Ubuntu is released.

**Comment by senorprogrammer** [comment]
Ah cool. I don't have access to a Windows machine so any help that Windows users can provide in trying out WTF on Windows is much appreciated.

**Comment by senorprogrammer** [comment]
Has anyone still paying attention to this thread tried to get WTF running under Windows r1905 per @mxplusb's comment above? I'd love to know if you've had any success.

**Comment by mxplusb** [comment]
I can take a look at it later today (assuming I remember).

**Comment by mxplusb** [comment]
Here is what it looks like under build 18936. About the same as when I filed this issue.

![image](https://user-images.githubusercontent.com/7537841/61101568-7ed3cb80-a427-11e9-8e42-97fdce7fe9a5.png)

**Comment by mxplusb** [comment]
Apparently I spoke too soon, it just panicked.

![image](https://user-images.githubusercontent.com/7537841/61101662-d6723700-a427-11e9-8b7f-960c25fd0e52.png)

```
panic: runtime error: index out of range
goroutine 23 [running]:
github.com/rivo/tview.(*TextView).Draw(0xc42018c410, 0xc629e0, 0xc42007b380)
/mnt/p/go/src/github.com/rivo/tview/textview.go:738 +0x13cc github.com/rivo/tview.(*Grid).Draw(0xc420170360, 0xc629e0, 0xc42007b380)
/mnt/p/go/src/github.com/rivo/tview/grid.go:582 +0x1514 github.com/rivo/tview.(*Pages).Draw(0xc4201843f0, 0xc629e0, 0xc42007b380)                                                                                                /mnt/p/go/src/github.com/rivo/tview/pages.go:246 +0xf9 github.com/rivo/tview.(*Application).Draw(0xc4201803f0, 0x0)                                                                                                        /mnt/p/go/src/github.com/rivo/tview/application.go:265 +0xcf main.redrawApp(0xc4201803f0)
/mnt/p/go/src/github.com/senorprogrammer/wtf/wtf.go:94 +0xd1 created by main.main
/mnt/p/go/src/github.com/senorprogrammer/wtf/wtf.go:231 +0x330
```

**Comment by doxxx** [comment]
The entire WTF UI visibly repaints once a second -- probably when the data displayed is updated. It also happens in bursts during startup, which lends credence to the on data update theory. This occurs for me in PowerShell 5 and 6 in both the normal Windows console and the new Windows Terminal, on Windows 10 1903.

If I can figure out how to capture a video demonstrating it, I'll post it.

**Comment by doxxx** [comment]
So, this is interesting. I originally reported this bug from my work laptop, running Windows 10 Enterprise 1903. I just tried it at home on Windows 10 Home 1903 using PowerShell 5 in Windows Terminal, and it _does not flicker_.

So there's something else at play here.

**Comment by doxxx** [comment]
I noticed something else, just a small bug:

![image](https://user-images.githubusercontent.com/677940/63899108-9f50e880-c9c9-11e9-88f9-ba3108ae1754.png)

The top right corner of the box is not drawn correctly. If I resize the window, I can briefly see that it's drawing the top of the box one character too long, so the corner box character is being cut off on the right side of the window.

**Comment by mxplusb** [comment]
I checked this on my Mac with `dev`, and I didn't see this behaviour, so it must be specific to Windows.

If I remember, I will check on this either later tonight or tomorrow. Seems Windows-specific. I have a few theories but will have to do some digging and testing.

**Comment by ragebflame** [comment]
I am seeing the flickering also.
- Windows 7 
- Cmder v1.3.12

**Comment by glennsarti** [comment]
So it looks like WTF cannot even be built on Windows anymore from v0.33.0 onwards 😢😢😢.  My suspicion is https://github.com/wtfutil/wtf/commit/e23cec28971c6d5612a0b8b2c01d217aa6bc0efd has broken it due to `.Start` not being exposed on Windows systems.

Also creack/pty does not appear to support Windows correctly anyway (https://github.com/creack/pty/issues/95)

After reading through the comments something that struck me was the conflating of Shell, Terminal and Console. (yay for naming things!).  e.g. Using PowerShell (the shell) in the newer Windows Terminal (which has the pty support).  doxx did a good job differentiating that in their testing. Need to be careful of that.


```
C:\Source\tmp\wtf [master ≡]> git reset --hard v0.33.0
HEAD is now at b333a149 Update CHANGELOG.md
C:\Source\tmp\wtf [master ↓82]> go install
go: downloading github.com/xanzy/go-gitlab v0.38.1
...
# github.com/wtfutil/wtf/modules/cmdrunner
modules\cmdrunner\widget.go:146:12: undefined: pty.Start
C:\Source\tmp\wtf [master ↓82]> git reset --hard v0.32.0
HEAD is now at 9c9446fc fixing goreleaser config
C:\Source\tmp\wtf [master ↓182]> go install -v
go: downloading github.com/gdamore/tcell v1.3.0
...
C:\Source\tmp\wtf [master ↓182]> 
```

**Comment by bitcrazed** [comment]
@glennsarti:

> something that struck me was the conflating of Shell, Terminal and Console. (yay for naming things!)

TELL ME ABOUT IT! :) This is one of the reasons I wrote a [multi-part blog series](https://devblogs.microsoft.com/commandline/windows-command-line-backgrounder/) on the history, evolution, and internal architecture of the Windows command-line, concluding with [the post announcing the new ConPTY](https://devblogs.microsoft.com/commandline/windows-command-line-introducing-the-windows-pseudo-console-conpty/).

Alas, for naming, I often say:
[![image](https://user-images.githubusercontent.com/961950/109088229-e3f33800-76c3-11eb-8c76-f1f39f4b8a2b.png)](https://twitter.com/richturn_ms/status/1126011884203794433)

As per my prior suggestion (though [I don't see this issue referenced in the Terminal repo right now](https://github.com/microsoft/terminal/issues?q=is%3Aissue+https%3A%2F%2Fgithub.com%2Fwtfutil%2Fwtf%2F+)) - if you're able to reliably repro this problem, please do file an issue in [the Windows Terminal repo](https://github.com/microsoft/terminal). This is where the team that owns the legacy Windows Console, the new Windows Terminal, and all of Windows' Command-line infrastructure live. If this is an issue with the Console/Terminal, as opposed, for example, to VT causing an expected full refresh, the team will be happy to work with you to figure out a fix, as schedules etc. allow.

> Also note that since Terminal is open-source, and should you be sufficiently interested in this issue, you can also clone and build your own Windows Terminal and set breakpoints to debug the issue and find out what's causing the full-frame refresh. 

HTH.

**Comment by eabase** [comment]
Any news here?
