### ISSUE TITLE
CircleCI Module

### ISSUE THREAD

**Issue by ejdunn2001** [wtfutil/wtf#1044]
I am getting an error: 
http: read on closed response body

**Comment by senorprogrammer** [comment]
Thanks for filing this. I'll try and take a look.

**Comment by yanivmo** [comment]
Seems like the deferred close, introduced in #1036, closes the body on return from `circleRequest`, before the body is actually read.

**Comment by dabcoder** [comment]
@yanivmo thanks for the heads up, will look into this since I introduced it in the aforementioned PR. Interested in getting feedback with regards to where/when to actually close the response body if you already have a fix in mind.

**Comment by LKaemmerling** [comment]
The same issue was/is living in the HackerNews module. I opened up an MR with a fix for this:
https://github.com/wtfutil/wtf/pull/1063

**Comment by dabcoder** [comment]
@LKaemmerling Thanks for fixing this in the HN module, looks like we could do the same for this module too? Opened #1065 as a follow up.

**Comment by senorprogrammer** [comment]
Looks like this has been fixed in the CircleCI module.
