### ISSUE TITLE
[utils] Provide a unified http(s) request wrapper

### ISSUE THREAD

**Issue by dabcoder** [wtfutil/wtf#1051]
## What should it do?

I was wondering what your thoughts would be on creating something like an http request wrapper in `utils/`that folks could use to make requests to external endpoints/services (when an API client for such endpoints/services is not already used to take care of that). 
At the moment such clients are created in modules that need them, and it's easy to forget to close the response body, and there's a variety of (similar) implementations I think, for instance: https://github.com/wtfutil/wtf/blob/6ecec4f14908adab784c36152c6b01cf0e91091d/modules/finnhub/client.go#L59-L79 or https://github.com/wtfutil/wtf/blob/6ecec4f14908adab784c36152c6b01cf0e91091d/modules/bamboohr/request.go#L9-L28. 

So that'd be something like:

```
func MakeRequest(method string, url string, headers // not sure about that one) (*http.Response, error) {
...
    return response, error
}
```

**Comment by senorprogrammer** [comment]
I think that would be incredibly useful and really help to simplify the creation of modules.

**Comment by dabcoder** [comment]
Good to hear, I can certainly look into this a bit more. Any suggestions with regards to the implementation?

- Should it be a function or a method with a receiver? The former might be simpler as I am not sure what type/struct would need to be used.
- How should secrets/credentials (keys) be handled, if at all?
- Anything to keep in mind performance wise, things not to do?

**Comment by senorprogrammer** [comment]
Haven't really though about any of that. My advice would be to start with two of the simpler modules that could take advantage of it, and get it working for those, and then it can be extended and layered on to others over time. Performance-wise, other than "no sleeps in the main routine :)", there's probably not very much to worry about.

**Comment by senorprogrammer** [comment]
Keeping this open.
