### ISSUE TITLE
Documentation about clock seems broken

### ISSUE THREAD

**Issue by ReneFroger** [wtfutil/wtf#1054]
## What's broken?

When I navigate to the [module documentation](https://wtfutil.com/configuration/files/modules/clocks/) about clock, I see the following:

![image](https://user-images.githubusercontent.com/5211845/107123749-92634480-689f-11eb-87fb-81b74bf922b9.png)
![image](https://user-images.githubusercontent.com/5211845/107123752-9a22e900-689f-11eb-9548-85f790bc088f.png)

I assume this is not how it should look. I see the same in multiple browsers: Google Chrome and Mozilla Firefox. The other documentation about other module looks fine though.

**Comment by dabcoder** [comment]
The modules documentation pages lives under `https://wtfutil.com/modules/<module-name>`, not under `https://wtfutil.com/configuration/files/modules/<module-name>/`. However, it looks like there is an issue to render files under the `https://wtfutil.com/configuration/files/modules/<module-name>/` path (not just the clocks module). I don't know where the issues lies, but it's an issue for https://github.com/wtfutil/wtfdocs.

**Comment by senorprogrammer** [comment]
Thanks for pointing this out. This is fixed now.
