### ISSUE TITLE
Potential Bug Risks and Anti-Patterns

### ISSUE THREAD

**Issue by HarshCasper** [wtfutil/wtf#1059]
## Description 

Hi 👋 

I ran DeepSource Static Code Analysis upon the Project, the results for which are available [here](https://deepsource.io/gh/HarshCasper/wtf/). 

The Static Code Analysis Tool found potential bugs and anti-patterns in the Code, that can be detrimental at a later point in time with respect to the Project. DeepSource helps you to automatically find and fix issues in your code during code reviews. This tool looks for anti-patterns, bug risks, performance problems, and raises issues. 

Some of the notable issues are: 

- Calls to exit/fatal made in function using defer [here](https://deepsource.io/gh/HarshCasper/wtf/issue/CRT-D0011/occurrences)
- Shadow of builtin detected [here](https://deepsource.io/gh/HarshCasper/wtf/issue/CRT-A0001/occurrences)
- Empty String Tests [here](https://deepsource.io/gh/HarshCasper/wtf/issue/CRT-A0004/occurrences)
- Bad TLS Connection Settings [here](https://deepsource.io/gh/HarshCasper/wtf/issue/GSC-G402/occurrences)

There are plenty of other issues in relation to Bug Discovery and Anti-Patterns which you would be interested to take a look at.

If you would like to integrate DeepSource to autofix some of the commonly occurring issues, I can help you set that up :)

**Comment by senorprogrammer** [comment]
Apologies for the delay. This seems very cool, I like it a lot. Having it automated on PRs would be very beneficial.

**Comment by senorprogrammer** [comment]
Added.
