### ISSUE TITLE
Jira auth with PAT

### ISSUE THREAD

**Issue by avdv** [wtfutil/wtf#1060]
## What should it do?

Currently, I have to use username : password authentication with basic auth.

It would be nice to also accept a personal access token in order to not having to expose full login information.

PTAs can be used via the Authorization header, see https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html#UsingPersonalAccessTokens-UsingPATs

**Comment by Seanstoppable** [comment]
@avdv Isn't this already supported with the `apiKey` setting for the JIRA module?

**Comment by avdv** [comment]
> @avdv Isn't this already supported with the `apiKey` setting for the JIRA module?

@Seanstoppable it seems that the apiKey setting is just a (non-intuitive) alias for "password". This is then used in a basic auth with "email" as username.

See https://github.com/wtfutil/wtf/blob/21ab01c7cf8073136ffad6e8bd5217d797cb8959/modules/jira/client.go#L66

With a token, you would no longer need a username to authenticate.
