### ISSUE TITLE
IPInfo module doesn't refresh

### ISSUE THREAD

**Issue by dithmer** [wtfutil/wtf#1067]
## What's broken?
If I am switching my outgoing ip address by for example using a vpn, I would expect, that at least a force refresh of my board leads to having the ipinfo information to be updated. In real that doesn't happens and the ipinfo stays the same until I restart the dashboard.

**Comment by senorprogrammer** [comment]
I'm unable to reproduce this. In my case it displayed both IP addresses without restart. Could you post your `ipinfo` config here?
