### ISSUE TITLE
May I ask for an Odoo dashboard?

### ISSUE THREAD

**Issue by nhomar** [wtfutil/wtf#1069]
## What should it do?

Tasks Open.
TODO pending.
Unread notifications.

Some Instances stuff (for sysadmin).

We have something like newrelic but for our odoo instances.

We can finance the development if necessary, Is that possible?

**Comment by senorprogrammer** [comment]
I think that would definitely be a useful module. I don't use Odoo so I won't be doing it but perhaps someone else will. If you're amenable, I'll publicize this a bit and we'll see if someone else takes you up on it. What do you think?

**Comment by nhomar** [comment]
Hello.

I actually know Odoo VERY well.....

I can explain/document/do the odoo layer, I need an expert in WTF that help me to do it human readable and human usable...

If you help me yourself, I am pretty sure we can do a pretty nice job (and I would love to pay for your time to be sure it is properlly financed and opensourced).

What do you think?

**Comment by nhomar** [comment]
Hello.

May you kindly point me out to the right person and we can work on this....

THanks a lot!

**Comment by senorprogrammer** [comment]
I think we should leave this one open. It's a good idea, and someone familiar with Odoo might be interested in it.
