### ISSUE TITLE
Jenkis apiKey - found character that cannot start any token

### ISSUE THREAD

**Issue by delpes** [wtfutil/wtf#1073]
I am currently using Jenkins 2.235.1 and am generating an api token as described here: https://www.jenkins.io/blog/2018/07/02/new-api-token-system/

This gives me a token in the style `[0-9a-f]{34}`

Setting this token in the config files gives me the following error:
`Error: yaml: line 50: found character that cannot start any token`

Expected behavior:
Accept Jenkins Api Token format.

It doesn't seem to me that the format of the api token for jenkins hasn't changed in a while but i haven't found any issues in it not working. Am i doing sth wrong or does the validation for the apiKey in the jenkins module need an update?

**Comment by senorprogrammer** [comment]
Could it be that you have malformed yaml? Have you run your config through a YAML validator?

**Comment by senorprogrammer** [comment]
Closing this as stale.
