### ISSUE TITLE
Pass OPML configuration for feedreader

### ISSUE THREAD

**Issue by sreeram-boyapati** [wtfutil/wtf#1076]
## What should it do?
Many applications like news flash allow us to export feeds configuration as OPML files.

Is it possible to read from an OPML file for feedreader module in wtfutil?

**Comment by sreeram-boyapati** [comment]
and If possible, implement caching?

**Comment by senorprogrammer** [comment]
This isn't supported by the feedreader module at the moment. That might be a decent addition for sure.
