### ISSUE TITLE
Documentation for configuring secret store

### ISSUE THREAD

**Issue by sreeram-boyapati** [wtfutil/wtf#1078]
## How can we help?

I could not find the documentation to configure secret store for storing API keys. I am getting the following error while I am trying to save a secret against a module

```
Saving secret for service "jira": cannot store secrets: wtf.secretStore is not configured
```

**Comment by senorprogrammer** [comment]
This isn't documented yet, and it should be per this issue on the documentation https://github.com/wtfutil/wtfdocs/issues/97

Hopefully there's enough detail in this conversation https://github.com/wtfutil/wtf/issues/517 for you to work it out until there is documentation.
