### ISSUE TITLE
Case-insensitive important configuration fields

### ISSUE THREAD

**Issue by senorprogrammer** [wtfutil/wtf#1079]
## What should it do?

The configuration is case-sensitive, which is problematic because the distinction between something like "refreshInterval" and "refreshinterval" is very subtle, and the configuration is not consistent with camel-casing config values.

Either raise a configuration error if this value is lower-cased, or better yet, just support any variation of "RefreshINTerval" (and other important ones that might be affected the same).

**Comment by noxer** [comment]
I'd like to tackle this but that may require me to rewrite the github.com/olebedev/config package and subsequently all the imports. Would a change of this scope be acceptable for merge?
