### ISSUE TITLE
feedreader module - Line breaks in titles

### ISSUE THREAD

**Issue by ajh-sr** [wtfutil/wtf#1088]
I'm not sure if this is a bug or if this is expected? Or if medium.com's feed is malformed? 

## What's broken?
![image](https://user-images.githubusercontent.com/71472057/120714076-da753980-c516-11eb-82f1-43ee0d3ff35a.png)

The article: [Top Contributors Impacting
Your Real-Time Application
Performance](https://subspacepowered.medium.com/top-contributors-impacting-your-real-time-application-performance-87e96676b2c7)

**Comment by senorprogrammer** [comment]
Frankly, I'm surprised there are line breaks in a feed item title. That seems weird. But WTF should also handle that gracefully so I'm going to label this a bug and see about getting a fix for it.

**Comment by GibranHL0** [comment]
Hey 👋, I'm new to the project and I'd like to contribute.
Could you assign me this issue?

**Comment by senorprogrammer** [comment]
Great! It's all yours.

**Comment by GibranHL0** [comment]
Thanks, I'll comment proposal as soon as possible.

**Comment by ajh-sr** [comment]
🙇  Thanks @GibranHL0

**Comment by senorprogrammer** [comment]
If you've got an idea for a fix, feel free to submit a PR. No need to propose, it's not that formal here :)

**Comment by GibranHL0** [comment]
Opened a PR #1090

**Comment by senorprogrammer** [comment]
Fixed by https://github.com/wtfutil/wtf/pull/1090
