### ISSUE TITLE
Anyway to change the default colors?

### ISSUE THREAD

**Issue by jim-at-jibba** [wtfutil/wtf#1089]
Is there anyway to change the default colors (red, green, yellow). 

Thanks

<img width="309" alt="image" src="https://user-images.githubusercontent.com/7897877/122628647-298ea300-d0af-11eb-92ec-09f9b4ff8a32.png">

**Comment by senorprogrammer** [comment]
I take it this is the Jira module? Looks like the colours are hard-coded in for those lines: https://github.com/wtfutil/wtf/blob/91942b68f203aa95e43dfa637165f0136a9343da/modules/jira/widget.go#L87

**Comment by jim-at-jibba** [comment]
Ok thanks.
