### ISSUE TITLE
Allow multiple widgets to be displayed in the same area

### ISSUE THREAD

**Issue by flw-cn** [wtfutil/wtf#1093]
## What should it do?

Multiple widgets can be swapped automatically between each other or with shortcut keys. Just like [textfile](https://wtfutil.com/modules/textfile/) does. The widgets can be of any existing type.

My real scenario was that I wanted to view multiple text files via `tail -f`, which also allowed wtfutil to be integrated into my tmux, along with other applications, to make up my final UI.

Since screen space is limited, I prefer to display multiple logs reflecting different content separately, and just press a shortcut when I need to view another one.

**Comment by senorprogrammer** [comment]
I'm not understanding something about the problem you're describing. You're using `tail -f` to follow multiple text files - are you viewing those in WTF via the command runner module? Or via the textfile module?

**Comment by flw-cn** [comment]
For example, if I have two text files of similar nature, I can use the same textfile to view them in order to save screen space, and when I need to switch, I just focus on the textfile and press the shortcut key.

However, if I have two log files of similar nature, I can monitor its changes with `tail -f`, but I can't put them in the same area (as textfile does), which means that it takes up double the screen space. Well, if it's three files then it will take up three times the screen space, etc.

The reason why textfile can support viewing multiple files at the same time is that it provides this feature itself. But I was wondering if it would be possible to make "displaying the content of multiple widgets in one area" a feature that would be available to all widgets.

To do this, we might need to have a container-like widget that allows multiple parallel widgets to be placed in it, forming a hierarchy, and then a shortcut in the container to toggle which widget is visible and which other widgets are hidden at the same time. Of course, it can also be made to switch automatically at intervals (like some of the dashboards you see in life).

Anyway, thanks for listening to my suggestion and for tagging it.

**Comment by senorprogrammer** [comment]
That's an interesting idea, I'd never thought of that. I suspect that would require an overhaul of the config system (not necessarily a bad thing). I'm going to think about this some more.
