### ISSUE TITLE
Feedreader throwing 404

### ISSUE THREAD

**Issue by celestial-30** [wtfutil/wtf#1096]
The feed reader module is throwing a 404 error. 
fresh install via homebrew, default config.yml file.
Only contriving factor i can think of is that I am running it on an apple m1 macbook air.

**Comment by senorprogrammer** [comment]
Could you provide a screenshot of what you're seeing? A 404 is an HTTP error, which suggests the feed endpoint no longer exists, but I'd like to see what's on screen.

**Comment by celestial-30** [comment]
<img width="454" alt="Screen Shot 2021-08-07 at 09 55 02" src="https://user-images.githubusercontent.com/52493158/128574906-3237b8be-cd8f-47e5-b355-fcf8a19d2731.png">
Here you go. Im looking for a log file now, i will post it when i find it.

**Comment by senorprogrammer** [comment]
Confirmed. I'm setting up a new machine and just ran into this.
