### ISSUE TITLE
refreshInterval less than 1 second

### ISSUE THREAD

**Issue by reportaman** [wtfutil/wtf#1103]
I know this might sound crazy for a dashboard, but some modules can happily take a refresh rate of less than 1 second. It can be a stopwatch for instance...

**Comment by noxer** [comment]
Maybe this could be implemented by adding an 'RefreshUnit' field to the common config and then multiplying 'RefreshInterval' with it.

**Comment by senorprogrammer** [comment]
Before tackling this problem at all, I'd like to see a few valid use-cases for a faster refresh rate that have a practical application. I'm not yet convinced this is a problem worth solving.

**Comment by senorprogrammer** [comment]
Solved by @ResamVi. Configurations now support an optional time unit, ie: `50ms, 5s`, etc. A single integer will still be interpreted as seconds.

**Comment by reportaman** [comment]
@senorprogrammer @ResamVi Thanks, works well!!!
