### ISSUE TITLE
Having issue with installion (Installing from source)?

### ISSUE THREAD

**Issue by vaibhav135** [wtfutil/wtf#1136]
## How can we help?
Hi, I've recently started looking on OpenSource. And I've come across this project, enough to say I don't have any experience in go whatsoever. I looked at the contributing guidelines.
I followed the [instruction here](https://github.com/wtfutil/wtf#installing-from-source). So my installed directory is ~/go/pkg/mod/github.com/wtfutils/wtf@v[version no. here] then I did => `make install` 

result of `make install`.
![image](https://user-images.githubusercontent.com/39329182/137694466-5bf8d866-cf5d-40c7-a8b8-6f8c8f0548ac.png)

but doing `make run`  is giving some error? here is the error that I am getting.

![image](https://user-images.githubusercontent.com/39329182/137694635-2368e8db-8633-4c32-9f04-00d01102977d.png)

**My second question** is:  say I did some changes In the code how do I push the code. I mean since I am not cloning the project itself from GitHub. I mean how does the push and pull thing work here. Maybe am confused here. So do I just simply need to do `git init` then do the general thing or is there any other thing to do in order to push/ pull code? I apologize for my lack of knowledge here, since I am new to this.
Thank you.

**Comment by senorprogrammer** [comment]
Hi @vaibhav135 is this still an issue?
