### ISSUE TITLE
BarGraph from CSV

### ISSUE THREAD

**Issue by Justinzobel** [wtfutil/wtf#1156]
## What should it do?
Show the BarGraph module but allow user to put in their own values from a csv file:

e.g
SomeServerCPU,30
SomeServerRAM,24
SothOtherSrvCPU,99

Allow setting of bar colour based on value,
0-10 green
11-20 yellow-green
...
91-100 red etc

Show the values in the bargraph updated at $interval.

**Comment by senorprogrammer** [comment]
This sounds like a new module to me, one that leverages the underlying BarGraph module.

**Comment by Justinzobel** [comment]
Indeed. I already have the bash scripts to pull the csv data and output it in a bargraph:
![image](https://user-images.githubusercontent.com/1370117/145501606-ad237edc-81af-484b-9f6e-5c67ef3c0997.png)
