### ISSUE TITLE
example of feedreader config for credentials

### ISSUE THREAD

**Issue by pcause** [wtfutil/wtf#1158]
## How can we help?
Unfortunately I don't know Go, so can you give an example of how to enter credentials for feedreader please.  And what if there are 3 feeds and the 1st and 3rd need credentials but 2nd doesn't.  Or just the 2nd of 2.

**Comment by senorprogrammer** [comment]
This should definitely be in the documentation, however in the meantime, here's the PR that added this functionality. It contains an example: https://github.com/wtfutil/wtf/pull/1133
