### ISSUE TITLE
Homebrew Warning while upgrading wtfutil

### ISSUE THREAD

**Issue by johnrm9** [wtfutil/wtf#1159]
While updating Homebrew I got this warning message:
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the wtfutil/wtfutil tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/wtfutil/homebrew-wtfutil/wtfutil.rb:9

**Comment by senorprogrammer** [comment]
I think this is because my local version of [goreleaser](https://goreleaser.com) is pretty old. I'm installing the newest version and I expect the next rerelease of WTF (in which the homebrew cask is create) should address this. I'll keep this open until this is proven. Thanks for reporting it!
