### ISSUE TITLE
Filter TODO using Tags

### ISSUE THREAD

**Issue by igbanam** [wtfutil/wtf#1172]
## What's broken?
Filtering using Tags

When I filter using `f` you can filter which of the todo has the filter string as part of it. I assumed this was the same thing for tags. But when I filter using `#`, the display updates with the proper tag to filter by, but the todo list remains the same.

I tried poking through the code to figure this one out, but my go-fu wasn't strong enough

**Comment by senorprogrammer** [comment]
Seems still relevant

**Comment by xavier-balesi** [comment]
I have the same issue.
filtering tags with `#` doesn"t works well. Sometimes it doesn"t filter and sometimes it filter just a part of tagged notes :
![image](https://user-images.githubusercontent.com/68602306/177659601-5de5fe50-498a-4456-8b1e-6b9cae2043d3.png)
