### ISSUE TITLE
The "uptime" cmd from the default config is not working

### ISSUE THREAD

**Issue by ezradiniz** [wtfutil/wtf#1197]
## What's broken?
The [uptime](https://github.com/wtfutil/wtf/blob/edad1b155d729dbafeb5dcdfca864a52d8151c62/cfg/default_config_file.go#L95)  cmd is not working properly, it is showing `exit status 1` 

But it works if I remove the empty string `""` from the args:
```
args: [""]
cmd: "uptime"
```
Args without `""`
```
args: []
cmd: "uptime"
```

**Comment by felicianotech** [comment]
What version of wtf are you running?
What's your OS and OS version?

---

This is working for me out of the box so I'm trying to determine what might be different here.

**Comment by brandonwardlaw** [comment]
Same issue here. Noted tweak above works for me. 

System info: 
```
❯ uname -a
Linux <hostname> 5.15.0-30-generic #31-Ubuntu SMP Thu May 5 10:00:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
❯ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy
❯ wtfutil --version
0.41.0 (2021-12-28T22:54:23Z)
```

**Comment by umop3plsdn** [comment]
just wanted to comment and say this issue still exists for some reason with a new install

**Comment by toby-bro** [comment]
Yes it is because of this : 
https://github.com/wtfutil/wtf/blob/6a02b971f042b8c689237d2cc1d3c11f37361860/cfg/default_config_file.go#L93-L94 
did you do a local install with `go install .` to install wtf ?
