### ISSUE TITLE
Keyboard controls no longer work

### ISSUE THREAD

**Issue by senorprogrammer** [wtfutil/wtf#1221]
## What's broken?

The latest upgrade to tview v2 seems to have broken keyboard movement within modules. Arrow keys no longer work and the Esc key no longer gives up focus.

**Comment by Seanstoppable** [comment]
Potentially related to https://github.com/wtfutil/wtf/issues/1140, which I ran into in my attempt.

**Comment by senorprogrammer** [comment]
That makes sense. I'm hoping to dig into this next week to see if I can find a solution.

**Comment by senorprogrammer** [comment]
Keyboard controls for navigating between widgets works (number keys) as long as no key controls for the widget are used. Once one of the widget's key controls are used, keyboard access is lost

**Comment by senorprogrammer** [comment]
Keyboard controls for navigating between widgets works (number keys) as long as no key controls for the widget are used. Once one of the widget's key controls are used, keyboard access is lost

**Comment by senorprogrammer** [comment]
The problem seems to have something to do with the execution of the assigned key function:

```
	fn = widget.keyMap[event.Key()]
	if fn != nil {
		fmt.Println(">> keymap")
		fn()
		return nil
	}
```

If `fn()` is commented out, things are fine.

**Comment by senorprogrammer** [comment]
The problem seems to have something to do with the execution of the assigned key function:

```
	fn = widget.keyMap[event.Key()]
	if fn != nil {
		fmt.Println(">> keymap")
		fn()
		return nil
	}
```

If `fn()` is commented out, things are fine.

**Comment by senorprogrammer** [comment]
Calling `widget.display()` from within a keyboard key function causes the hang, perhaps a circular redraw loop of some kind?

**Comment by senorprogrammer** [comment]
Calling `widget.display()` from within a keyboard key function causes the hang, perhaps a circular redraw loop of some kind?

**Comment by senorprogrammer** [comment]
Calling `fn()` from within `keyboard_widget.InputCapture()` causes it to hang....

**Comment by senorprogrammer** [comment]
Calling `widget.tviewApp.QueueUpdateDraw(func() {`, even when that block is empty, causes the hang.

**Comment by senorprogrammer** [comment]
Related to this? https://github.com/rivo/tview/issues/199

**Comment by senorprogrammer** [comment]
Calling `widget.tviewApp.Draw()` also hangs it. Commenting all the `*Draw` functions gets the app working again, but modal dialogs etc. no longer render to screen until after the first keyboard press in them.

**Comment by senorprogrammer** [comment]
Also this issue https://github.com/rivo/tview/issues/569

**Comment by senorprogrammer** [comment]
Problem now is: how to get modal dialogs to draw onscreen _before_ the user presses a first keypress (the keypress causes a draw which then renders the entire screen, but after the fact).

**Comment by senorprogrammer** [comment]
Fixed.

**Comment by senorprogrammer** [comment]
Fixed.

**Comment by senorprogrammer** [comment]
v0.42.0 has been released, which fixes this https://github.com/wtfutil/wtf/releases/tag/v0.42.0
