### ISSUE TITLE
Getting "429 Too Many Requests" when using subreddit module

### ISSUE THREAD

**Issue by michaelMinar** [wtfutil/wtf#1234]
I recently saw that the subreddit module stopped working for me. When enabled all of these modules, regardless of subreddit chosen or refresh rate give back a "429 Too Many Requests". I've disabled all but one in my config, so it isn't likely an issue with multiple modules running at once.

**Comment by Seanstoppable** [comment]
I can't replicate, do you mind sharing a portion of your config?

**Comment by michaelMinar** [comment]
Sure, thanks for taking a look. Here is the section of my config

    news:
      type: subreddit
      enabled: true
      numberOfPosts: 10
      position:
        top: 9
        left: 6
        height: 2
        width: 6
      sortOrder: top
      subreddit: "news"
      topTimePeriod: "day"
      refreshInterval: 2600

**Comment by Seanstoppable** [comment]
I can replicate when recompiling with recent versions of go
Looks like it is this https://www.reddit.com/r/redditdev/comments/t8e8hc/getting_nothing_but_429_responses_when_using_go/

I'll have a fix soon.

**Comment by Seanstoppable** [comment]
Closed via #1239
