### ISSUE TITLE
JIRA module: support querying for issues / tasks not assigned to me 

### ISSUE THREAD

**Issue by willyspinner** [wtfutil/wtf#1254]
Hello! I love wtfutil, it's a great way to have everything all in one place. One feature enhancement I have:

## What should it do?

The jira module right now only supports querying issues assigned to the `username` (as per config), with an option to append the jql query. 

I'd like to search for a couple of things:
- issues that I created (reported), not necessarily assigned to anyone, that aren't closed / done.
- issues that I'm watching, also not necessarily assigned to me
etc.

Is there a way to provide the full jql query, instead of it being appended to issues assigned to `username`? 

Thanks ! 🙏

**Comment by willyspinner** [comment]
Oh wait, just realized in the code `modules/jira/client.go` that if you provide empty string (`""`) as username, the asignee won't be created. Can we make this clearer in the docs @senorprogrammer ?

**Comment by senorprogrammer** [comment]
Yep, I think that's an excellent idea.
