### ISSUE TITLE
Highlighted background row seems to spill over

### ISSUE THREAD

**Issue by zyrre** [wtfutil/wtf#1280]
Whenever a row is highlighted it seems that all following rows receive the HighlightedBackground color?
To illustrate, here I have row 5 highlighted:
![image](https://user-images.githubusercontent.com/2995732/179980927-e86006b9-7f83-4789-86a4-0f83c25da046.png)

There is no difference among modules, all that have row highlighting act the same.

Any idea what can cause this?

For info: I just cloned the repo and built it, ran bin/wtfutil.
Also, adding something like 
`colors:
    background: red`
to the config will change the background color, but adding this:
`colors:
    highlight:
      fore: red
      back: red`
does not change any of the colors.

**Comment by Seanstoppable** [comment]
Definately a regression.

Using git bisect, I've narrowed it down to the following. Unfortunately compile errors mean on most of these mean that I couldn't get a clean exact commit.
e72dcda1b777f711d8c3a0e7fd3e354e22be5c44 (changes to highlight and textwidget)
d3357e9d97844e141699614e2dd258a362fa9061 (probably not, as gitlab update)
9bba717e25b9cd6a76f1885188b07a452a8786a9 (Upgrade to tcell2, seems possible)
d7ccba4db9b3a305888af265ae20f0d972cff2e2 (Golang ci change, so unlikely)
4ef88b4d36234e2085eeddc2940266e3ba088863 (Godo upgrade, so unlikely)
bb31254b52b69d73b39766854e7c900b3675d226 (Go-pretty upgrade, which also seems possible culprit).

Will dig in more.

**Comment by senorprogrammer** [comment]
Nice find, I'm pretty sure it's the result of the cell upgrade. It seems a lot changed under the hood with /v2.

**Comment by senorprogrammer** [comment]
Fixed with https://github.com/wtfutil/wtf/pull/1300
