### ISSUE TITLE
Get more detail of jira ticket

### ISSUE THREAD

**Issue by tomzaku** [wtfutil/wtf#1305]
## What should it do?

In our jira system, we have a field called "Due Date" and I would like to show it in the dashboard. 

It would be greate if we support add more information of the ticket such as:

```
jira:
    fields: ["duedate", "assignee"]
```

I'm not good at golang. But I can give it a try. But may I know how can I create a new module or update jira module and try it from my machine

https://wtfutil.com/development/creating_new_modules/

**Comment by Seanstoppable** [comment]
If you want to give it a try, that would be great!

There are a few places I think you would need to edit
First would be to add a setting in [this file](https://github.com/wtfutil/wtf/blob/master/modules/jira/settings.go)
And then you probably have to modify [this function](https://github.com/wtfutil/wtf/blob/master/modules/jira/widget.go#L70-L101) to include them in the heading and details
