### ISSUE TITLE
Cant quit out of wtfutil

### ISSUE THREAD

**Issue by Moizsohail** [wtfutil/wtf#1318]
## What's broken?
If the internet is dead and as soon as I press ctrl+c on wtfutil, the util becomes unresponsive. 

<img width="735" alt="image" src="https://user-images.githubusercontent.com/32095770/185972021-1bb3e575-fd9a-4cb9-b673-0c2f50ed159e.png">

I am using M2 Monterey. I built wtfutil using `GOOS=darwin GOARCH=arm64 go build -o bin/${APP} `

**Comment by Seanstoppable** [comment]
Interesting. So to clarify, if your internet is all right, it closes fine?
If you just left it, does it eventually time out?
From the image, are you using one o the included configs, or are have you modified it. Which modules are running?

**Comment by senorprogrammer** [comment]
What happens if you press `q` with no module selected? Does that quit the app? (I cannot reproduce the issue you're seeing).
