### ISSUE TITLE
Trello module doesn't read env variables

### ISSUE THREAD

**Issue by the-it** [wtfutil/wtf#1333]
## What's broken?

The Trello module doesn't load its values from the environment variables as outlined in the [docu](https://wtfutil.com/modules/trello/). The API key could be a simple case of docu typing (app <-> api), but the access token also isn't picked up from env.

**Comment by Seanstoppable** [comment]
Ah, yes, looks like a typo in the docs. That should be API_KEY not APP_KEY.

**Comment by senorprogrammer** [comment]
@the-it Does this work for you using `API_KEY` instead?

**Comment by the-it** [comment]
Will check that

**Comment by the-it** [comment]
Yes, it works with the corrected typo. Let me craft a PR for this.

**Comment by the-it** [comment]
I see that @Seanstoppable already fixed this in https://github.com/wtfutil/wtfdocs/pull/153. So I would say this is closed then.
