### ISSUE TITLE
Documentation error in jira module

### ISSUE THREAD

**Issue by shitchell** [wtfutil/wtf#1335]
## What's broken?

It looks like the description for `domain` got copied to the `project` key in the [documentation](https://wtfutil.com/modules/jira/):

![image](https://user-images.githubusercontent.com/621412/188204561-bdf72412-d6eb-45b0-83c4-396c025213c8.png)

**Comment by bashbunni** [comment]
This fix was merged in the docs repo `wtfdocs`
