### ISSUE TITLE
Default config.yml still includes exchangerate module instead of yfinance

### ISSUE THREAD

**Issue by dixonge** [wtfutil/wtf#1347]
## What's broken?

Pretty much in the title...

**Comment by pliski** [comment]
The [default config file generator](https://github.com/wtfutil/wtf/blob/master/cfg/default_config_file.go) doesn't seems to have any reference to `exchangerate` nor `yfinance` module. 
The config file could have been migrated from an old one already present in the filesystem at the moment of the installation.
