### ISSUE TITLE
module todo : cannot use 'q' in todo item

### ISSUE THREAD

**Issue by xavier-balesi** [wtfutil/wtf#1350]
Hi and thank you for this very useful tool !

I encounter an issue with [module todo](https://wtfutil.com/modules/todo/) : I can't create a todo item with a `q` in name.

**Steps**
- select todo module in wtf
- type `n` to create a new item
- type `quickfix list`
- type `<CR>`

**Expected behaviour** 
A new item is created with name `quickfix list`

**Obtained behaviour**
- wtf exit when typing `q`

**Comment by senorprogrammer** [comment]
You're right about this one and the next release will have it fixes (the PR for that is here https://github.com/wtfutil/wtf/pull/1272).

Which is a great reminder for me, I'll try to put the next release out today.

**Comment by xavier-balesi** [comment]
Tested now : All is OK.
Thank you !

**Comment by senorprogrammer** [comment]
v0.42.0 has been released that fixes this https://github.com/wtfutil/wtf/releases/tag/v0.42.0
