### ISSUE TITLE
App startup time

### ISSUE THREAD

**Issue by alirezaalavi87** [wtfutil/wtf#1368]
Hi. and thanks for the great app.

So I have noticed that it seems like wtfutil doesn't start asynchronously; when I dont have internet access or internet access is corrupted, the app waits a long time to get started.
These are the modules that I use that need network:
- NBA Score
- pretty weather 
- hackernews

I feel like I should be able to see the rest of my modules while these modules are fetching data in the background.
I don't know if this is an issue with a module that I use or wtfutil.

**Comment by senorprogrammer** [comment]
The modules _should_ fetch async since each module is run in its own go routine, however it's definitely possible that those ones are blocking somehow.

**Comment by senorprogrammer** [comment]
Are you able to provide timing info between the two ways of starting up? I'm not able to reproduce this, however I don't use the modules you cite.

**Comment by alirezaalavi87** [comment]
Not sure how to do that but:
- with network and no VPN (I live in a country that these API's are blocked. there is network but they are blocked. I should have said it in the beginning) :  it takes about 28s for the app to startup.
- with network and VPN : app starts , some modules load, but some will halt for a couple of seconds until the modules that need networking are loaded.
- with no networking (turned off) : it starts instantly and shows error for those modules that require networking.
