### ISSUE TITLE
panic: runtime error: slice bounds out of range [:14] with length 11 [recovered]

### ISSUE THREAD

**Issue by vitosans** [wtfutil/wtf#1375]
## What's broken?

Fresh install from HomeBrew and binary from GitHub both show the same behavior. 

go version: go1.19.2 darwin/amd64

`goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1()
	github.com/rivo/tview@v0.0.0-20200108161608-1316ea7a4b35/application.go:149 +0x4d
panic({0x5626cc0, 0xc0000426a8})
	runtime/panic.go:1038 +0x215
github.com/wtfutil/wtf/modules/power.(*Widget).content(0xc0006a1f00)
	github.com/wtfutil/wtf/modules/power/widget.go:74 +0x43c
github.com/wtfutil/wtf/view.(*TextWidget).Redraw.func1()
	github.com/wtfutil/wtf/view/text_widget.go:49 +0x2a
github.com/rivo/tview.(*Application).QueueUpdateDraw.func1()
	github.com/rivo/tview@v0.0.0-20200108161608-1316ea7a4b35/application.go:493 +0x26
github.com/rivo/tview.(*Application).Run(0xc00041fa00)
	github.com/rivo/tview@v0.0.0-20200108161608-1316ea7a4b35/application.go:253 +0x5e8
github.com/wtfutil/wtf/app.(*WtfApp).Run(0xc0007bff08)
	github.com/wtfutil/wtf/app/wtf_app.go:80 +0x2e
main.main()
	github.com/wtfutil/wtf/main.go:64 +0x42a`

**Comment by cmollet** [comment]
Similar error on GH release binary for linux amd64.
```
go version go1.19.2 linux/amd64
```

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/wtfutil/wtf/app.NewDisplay({0x30ac6b8, 0x0, 0x0}, 0xc000b26620)
        /Users/chris/Projects/wtf/app/display.go:23 +0x1ca
github.com/wtfutil/wtf/app.NewWtfApp(0xc00063e300, 0xc000b26620, {0x7ffd3fcb54ab, 0x18})
        /Users/chris/Projects/wtf/app/wtf_app.go:52 +0x23e
github.com/wtfutil/wtf/app.(*WtfAppManager).MakeNewWtfApp(0xc000abff08, 0x0, {0x7ffd3fcb54ab, 0x18})
        /Users/chris/Projects/wtf/app/app_manager.go:28 +0xef
main.main()
        /Users/chris/Projects/wtf/main.go:56 +0x293
```



Unsure if related or not, but `go install github.com/wtfutil/wtf@latest` also fails with

```
go: downloading github.com/wtfutil/wtf v0.41.0
go: github.com/wtfutil/wtf@latest (in github.com/wtfutil/wtf@v0.41.0):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

**Comment by senorprogrammer** [comment]
This should be fixed in the next release via this commit https://github.com/wtfutil/wtf/commit/f73e9f4ebdacdb1a2f0a38cb7fefe37cc4819638

**Comment by senorprogrammer** [comment]
v0.42.0 has been released and should fix this https://github.com/wtfutil/wtf/releases/tag/v0.42.0
