### ISSUE TITLE
Kubernetes Module

### ISSUE THREAD

**Issue by spaghettifunk** [wtfutil/wtf#142]
### Feature Request
It would be nice to have a module to get the information about the resources in a kubernetes cluster.
Seeing the pods, deployments and such would be very nice but also, it would be rather cool to see the metrics of the resources regarding the nodes.

#### Summary
It should fairly simple to connect to the cluster by pointing to the `kubeconfig` file. Formatting when there are a lot of pods though, is quite a challenge I believe.

**Comment by steve-winter** [comment]
I am looking at this, and now have a version that can present Kubernetes info.

My view is it may be more relevant to just highlight counts of Pods in each state, and possibly wider resource information. Something like;
```
Namespace: my-namespace
Healthy Pods: 23
Unhealthy Pods: 2 (Everything that is not ready)
```
Uses k8s.io APIs which has added ~8mb in vendoring to project so far.

**Comment by senorprogrammer** [comment]
Added by @sudermanjr in https://github.com/wtfutil/wtf/pull/526
