### ISSUE TITLE
Configurable source title name for FeedReader

### ISSUE THREAD

**Issue by wijayaerick** [wtfutil/wtf#1451]
I've recently upgraded and noticed immediately that the FeedReader now also shows the source title. With multiple feeds, this is a nice feature. However, for a single feed, the source title feels redundant. 

<img width="967" alt="Screenshot 2023-01-03 at 2 42 03 AM" src="https://user-images.githubusercontent.com/20073050/210269364-8bdd1249-c10d-4967-9b60-f379f252c359.png"> 

Currently, is there a way to hide the source title?

# What should it do?

If there is no way to hide the source title, this ticket is a feature request to add a way to hide the source title. 
Perhaps a simple config `hideSourceTitle: bool` would do? 

I'm also interested in contributing once the approach is decided.

Related: https://github.com/wtfutil/wtf/pull/1171

**Comment by Seanstoppable** [comment]
I think the simplest thing might be to see how many feeds there are, and if there is only 1, suppress that?

**Comment by wijayaerick** [comment]
Closing this issue, as this is already added in https://github.com/wtfutil/wtf/pull/1449
```go
showSource bool `help:"Wether or not to show feed source in front of item titles." values:"true or false" optional:"true" default:"true"`
```
