### ISSUE TITLE
resourceusage isn't refreshing

### ISSUE THREAD

**Issue by berhram** [wtfutil/wtf#1458]
## What's broken?
resourceusage module seems to be broken: it is not updating itself, no matter what interval set. Update occur only when I scroll mouse wheel or press Ctrl-R or when any other widget is updated.
## Additional info:
OS: Fedora Linux 37 (Workstation Edition) x86_64
Installed from: homebrew/core

**Comment by Seanstoppable** [comment]
Interestingly, this is the only widget that is using the bargraph view. And it isn't just that the module is frozen, it isn't even selectable like other modules.

**Comment by Seanstoppable** [comment]
Actually, focusable was a red herring.

It seems to be related to the refreshInterval. At least, if I set a custom refresh interval for the widget, it works as expected.

**Comment by Seanstoppable** [comment]
So, the default refreshinterval is 300s (5 minutes). The global refreshinterval in the config no longer seems to really exist in code.
I am going to set a reasonable and overridable default refresh interval for resourceusage
