### ISSUE TITLE
looks weird ootb in light color schemes

### ISSUE THREAD

**Issue by donuts-are-good** [wtfutil/wtf#1613]
not sure if it is me or yall, but if it is yall, there you go.

<img width="1015" alt="image" src="https://github.com/wtfutil/wtf/assets/96031819/10796dfe-cee4-4463-ba56-70093e290cc5">

**Comment by senorprogrammer** [comment]
That does look weird. That said, WTF has no knowledge of the underlying colour scheme used by the terminal, it just has hard-coded colours for different elements. A theme-aware scheming mechanism would be an excellent improvement.

**Comment by SahilDahat** [comment]
what do you mean by theme-aware mechanism? Do you need some preset themes that could be directly applied?
