### ISSUE TITLE
Gitea integration

### ISSUE THREAD

**Issue by lunny** [wtfutil/wtf#164]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary
I would like wtf to add the support of [Gitea](https://gitea.io). Since Gitea has a similiar API with Microsoft-Github, I think that's some easy.

**Comment by senorprogrammer** [comment]
Please do, that would be great.

**Comment by schoenenberg** [comment]
I'm using gitea for awhile now and interested in adding the gitea integration.
Has anyone started developing this integration?

FYI:
Gitea provides a REST-API: [https://try.gitea.io/api/swagger](https://try.gitea.io/api/swagger)
