### ISSUE TITLE
Rare crash in text view drawing

### ISSUE THREAD

**Issue by baustinanki** [wtfutil/wtf#235]
#### What's the problem?

wtf crashes, randomly and after a long period of operation, with this callstack:

```
panic: runtime error: index out of range
goroutine 12 [running]:
  github.com/senorprogrammer/wtf/vendor/github.com/rivo/tview.(*TextView).Draw(0xc4201be0d0, 0x1753620, 0xc4200a76c0)
    ~/go/src/github.com/senorprogrammer/wtf/vendor/github.com/rivo/tview/textview.go:739 +0x1370
  github.com/senorprogrammer/wtf/vendor/github.com/rivo/tview.(*Grid).Draw(0xc4201a03f0, 0x1753620, 0xc4200a76c0)
    ~/go/src/github.com/senorprogrammer/wtf/vendor/github.com/rivo/tview/grid.go:582 +0x14ee
  github.com/senorprogrammer/wtf/vendor/github.com/rivo/tview.(*Pages).Draw(0xc4201b4750, 0x1753620, 0xc4200a76c0)
    ~/go/src/github.com/senorprogrammer/wtf/vendor/github.com/rivo/tview/pages.go:246 +0xf6
  github.com/senorprogrammer/wtf/vendor/github.com/rivo/tview.(*Application).Draw(0xc4201b1f80, 0x0)
    ~/go/src/github.com/senorprogrammer/wtf/vendor/github.com/rivo/tview/application.go:265 +0xcf
  main.redrawApp(0xc4201b1f80)
    ~/go/src/github.com/senorprogrammer/wtf/wtf.go:106
  created by main.main
    ~/go/src/github.com/senorprogrammer/wtf/wtf.go:264 +0x31712)(Z)
```

I've had this happen twice, both times after a couple days of uptime w/ no issues. The code where this occurs in `textview.go` is here:

```go
		// Get the text for this line.
		index := t.index[line]
		text := t.buffer[index.Line][index.Pos:index.NextPos]
```

I suspect the most likely reason for this is race conditions between text view drawing and text view updating - for example, if another routine was calling `SetText` on a text view while this code ran. It just occurred to me that I could build with `GOTRACEBACK=all` to get more detailed information on whether this is happening, so the next time this happens hopefully I can report back with more info.

**Comment by senorprogrammer** [comment]
Agreed. I've seen this and think your reasoning is sound. I haven't yet traced exactly where it's happening but I suspect adding a `mutex.Lock()` around the widgets that use `pages.go` might solve the issue.

**Comment by senorprogrammer** [comment]
This PR has been merged in to help improve the state of race conditions: https://github.com/wtfutil/wtf/pull/414

If you're able, pull master and give it a try. It will be included in the next WTF release.

**Comment by senorprogrammer** [comment]
Closing this out because 0.7.0 fixes this across the general case for widget rendering.
