### ISSUE TITLE
Multiple instances of textfile

### ISSUE THREAD

**Issue by alienrobotarmy** [wtfutil/wtf#309]
#### What problem does this solve?
This would allow multiple instances of textfile

#### How do envision it working?
Allow the user to add multiple textfile stanzas in the config.yml to allow displaying multiple text files

**Comment by iafan** [comment]
This looks like a duplicate of #181

**Comment by senorprogrammer** [comment]
With this PR https://github.com/wtfutil/wtf/pull/418 this is now possible. Documentation will be forthcoming.
