### ISSUE TITLE
Configure goreleaser to create docker image

### ISSUE THREAD

**Issue by senorprogrammer** [wtfutil/wtf#337]
#### What problem does this solve?

It would be great to be able to run wtf as a docker image rather than installing it locally every time. Handy for running different versions as well.

#### How do envision it working?

See this yo: https://goreleaser.com/docker/

**Comment by Seanstoppable** [comment]
@senorprogrammer Looks like this already happened?

**Comment by senorprogrammer** [comment]
There is a basic Docker file but the output is suspect at best. I doubt it currently works for anyone.

**Comment by senorprogrammer** [comment]
Docker file added and goreleaser target included.
