### ISSUE TITLE
Commute planning module

### ISSUE THREAD

**Issue by nicholas-eden** [wtfutil/wtf#342]
#### What problem does this solve?
Anyone who uses public transit probably checks their phone to check when the next bus or train is coming.  A module could display their upcoming options with some details like bus number or line, departure and arrival time.

This could have a configurable schedule for when it should display the time to get to work and the time to get home.

#### How do envision it working?
The user provides their home and work lat/log locations in the local config.  The module uses the OneStopAway, Google Maps API, or something similar to get commute information.

**Comment by robertmain** [comment]
Lots of public transit companies provide an RSS feed of the transit data. Therefore, I'd propose that #42 would be a good way to implement this
