### ISSUE TITLE
Confluence Task reader

### ISSUE THREAD

**Issue by BillKeenan** [wtfutil/wtf#346]
#### What problem does this solve?
We make heavy use of tasks in confluence from meeting notes and such, there is not api to pull them out, or wtf widget for them.

#### How do envision it working?
scrape a page
parse the tasks
display them sem-nicely

**Comment by BillKeenan** [comment]
it pulls from standard confluence task markup

<img width="1154" alt="screenshot 2018-11-25 00 33 04" src="https://user-images.githubusercontent.com/1319630/48975899-b41edb00-f049-11e8-98e1-81f0bfe434bf.png">

**Comment by senorprogrammer** [comment]
Cool, if you want to open a PR I'll definitely add this in.

**Comment by senorprogrammer** [comment]
Any of the above should work. You can point your upstream to the organization by changing it in `.git/config`, I believe you can still just push up to the `senorprogrammer` master and GitHub will do the right thing, or if you want you can start from a clean repo (assuming you have no changes you want to keep). Up to you.
