### ISSUE TITLE
Invalid Memory Address or Nil Pointer Dereference

### ISSUE THREAD

**Issue by danner26** [wtfutil/wtf#349]
#### What's the problem?
When running wtf version 0.4.0 it returns a runtime error: invalid memory address or nil pointer dereference

#### Operating system 
Distributor ID:	Ubuntu
Description:	Pop!_OS 18.04 LTS
Release:	18.04
Codename:	bionic

#### Terminal program & version
Built in terminal

#### WTF version
0.4.0

**Comment by senorprogrammer** [comment]
I haven't seen this issue in quite awhile and there's not enough info in this report to know exactly where it was happening. I suspect it's either a) fixed, or b) associated with the race conditions, in which case this is a dupe.
