### ISSUE TITLE
Date formatting

### ISSUE THREAD

**Issue by robertmain** [wtfutil/wtf#356]
#### What problem are you having and how can we help?

Trying to format the date to match the format in the screenshot [here](https://wtfutil.com/modules/github/) but I don't know what delimiters to use to get that. The ones in the example produce a very verbose date string with the time format included...

**Comment by robertmain** [comment]
Ah yeah - whoops! I meant to link to [this one](https://wtfutil.com/modules/git/)

**Comment by senorprogrammer** [comment]
[This line](https://github.com/wtfutil/wtf/blob/85efb48f5515dd984710c65540fc8347d35a92d6/git/git_repo.go#L52) is where that's defined. I'm basically handing off formatting responsibility to `git log`.

You can get the same result in the command line using this:
```
git log --date=format:"%b %d, %Y" --pretty=format:"%Cgreen %h %C(white) %s %C(dim)%an on %cd"
```
You can get that format in Go using the following format string: https://play.golang.org/p/lwMCZNl5iaX

**Comment by robertmain** [comment]
Ok. But as someone who doesn't know Go, I'm still none the wiser as to what delimiters to use. Is it just whatever you'd normally pass to git log?

**Comment by senorprogrammer** [comment]
I'm not sure what you mean by "delimiters" in this context. The way you tell Go to format a date string is a bit strange compared to other languages. You pass in a reference date and it uses that to figure out how to format. In this case, to get that output in Go, the reference date is `Format("Jan _2, 2006")`.

**Comment by robertmain** [comment]
Sure. I guess I was after something like [this](http://php.net/manual/en/datetime.createfromformat.php). It sounds like go doesn't do that though

**Comment by senorprogrammer** [comment]
Go has `time.Parse`: https://golang.org/pkg/time/#Parse
