### ISSUE TITLE
Jenkins Green Balls

### ISSUE THREAD

**Issue by skymeyer** [wtfutil/wtf#358]
Successful builds in the Jenkins module are using the blue color. Would like to add the option to use green instead of blue to mimic https://wiki.jenkins.io/display/JENKINS/Green+Balls.

**Proposal**
* Add a boolean greenBalls config parameter to use green instead of blue in reference to the green balls plugin
* Or add config parameters to be able to customize each colors

Thoughts ?

**Comment by rudolphjacksonm** [comment]
Hi folks--I'm learning Go and this seems like a good issue to take a stab at. @skymeyer having a boolean config parameter seems like the easiest place to start. Are you ok with me taking a look at this?

**Comment by rudolphjacksonm** [comment]
Also opened a PR for the wtfutildocs, see https://github.com/wtfutil/wtfdocs/pull/21

**Comment by senorprogrammer** [comment]
Thanks for tackling this one!

**Comment by senorprogrammer** [comment]
Closed with https://github.com/wtfutil/wtf/pull/403
