### ISSUE TITLE
ufw status bug in wtf

### ISSUE THREAD

**Issue by tupinek** [wtfutil/wtf#362]
Problem is, that wtf prints "Firewall: Enabled: Enabled" in situation when ufw is enabled and disabled.

Root cause is bad matching in https://github.com/wtfutil/wtf/blob/master/security/firewall.go#L53
In disabled state ufw returns string "Status: inactive".
In enabled state ufw reutrns string "Status: active".
Both are matched by code.

**Comment by senorprogrammer** [comment]
This PR has been merged into master, let me know if that resolves it for you 
https://github.com/wtfutil/wtf/pull/363/files
