### ISSUE TITLE
Opsgenie not working

### ISSUE THREAD

**Issue by GaboFDC** [wtfutil/wtf#364]
#### What's the problem?
Opsgenie api changed, the on-call endpoint was deprecated https://docs.opsgenie.com/docs/who-is-on-call-api#section-list-on-calls

```bash
curl -X GET 'https://api.opsgenie.com/v2/schedules/on-calls' --header 'Authorization: GenieKey xx-xx-xx-xx-xx'

{"message":"On-calls endpoint is not supported anymore.","took":0.007,"requestId":"xxx-5213-438c-91d6-xxx}
```

#### How did you expect it to behave?
Have to change the implementation to use new api

#### Operating system - Terminal program & version - WTF version
not relevant

**Comment by senorprogrammer** [comment]
Unfortunately I don't use OpsGenie anymore and have no API access so someone else will have to solve this one.

**Comment by senorprogrammer** [comment]
Thanks @GaboFDC, much appreciated
