### ISSUE TITLE
Make Error: character set not supported (Cygwin)

### ISSUE THREAD

**Issue by E3V3A** [wtfutil/wtf#367]
Following procedure in #350 results in the weird error:
`Error: character set not supported`

```bash
$ make run
go build -o bin/wtf
bin/wtf
C:\Users\XXXX\.config\wtf\config.yml
Error: character set not supported
make: *** [Makefile:35: run] Error 1
```
However, the binaries run fine anyway!

System: Cygwin/POSIX

How can I help debug?

**Comment by senorprogrammer** [comment]
Take a look at this thread, it might help. If it does or doesn't let me know: https://github.com/wtfutil/wtf/issues/225

**Comment by E3V3A** [comment]
As gadamore said: 
> Tcell, and hence wtf, won’t work with mingw inside mintty. 

However, another user [stated it was](https://user-images.githubusercontent.com/1605754/52144682-a3c84500-2624-11e9-89fa-104591262bc6.png) "working" in Zsh, but now I'm wondering if he was actually running Zsh in `ConEmu`. 

If there is no work-around to what gadamore said, then we can close this issue as `not supported / won't fix`.

**Comment by E3V3A** [comment]
Just FYI and from [Cygwin FAQ](https://cygwin.com/faq.html#faq.using.unicode):

> * `4.18` **Why don't international (Unicode) characters work?**
> 
> Internationalization is a complex issue. The short answer is that Cygwin 
> relies on the setting of the setting of LANG/LC_xxx environment 
> variables. The long answer can be found in the User's Guide in the 
> section Internationalization
> 
> Cygwin uses UTF-8 by default. To use a different character set, you need 
> to set the `LC_ALL, LC_CTYPE` or `LANG` environment variables.
> 
> * `4.19` **My application prints international characters but I only see gray boxes**
> 
> In the case of Cygwin programs, this likely means that the character set 
> as determined by the LC_ALL, LC_CTYPE or LANG environment variables does 
> not match the one set on the Text page of the Cygwin Terminal's options. 
> Setting the locale in the terminal's options will set the LANG variable 
> accordingly.
> 
> Non-Cygwin programs in the Cygwin Terminal do not usually take heed of 
> the locale environment variables. Instead, they often use the so-called 
> console codepage, which can be determined with the command:  
> `cmd /c chcp <codepage>`  
> followed by the appropriate Windows codepage number. The codepage number 
> for Cygwin's default UTF-8 character set is 65001.
>

**Comment by E3V3A** [comment]
Closing for now, as this **is a bug of tcell**. and not WTF.

**Comment by E3V3A** [comment]
There might have been some updates to `tcell` according to: 
* https://github.com/gdamore/tcell/issues/133

**Comment by senorprogrammer** [comment]
Good to hear. I'll update the tcell dependency and bring that in.

**Comment by senorprogrammer** [comment]
tcell has been updated to the latest and is in master.
