### ISSUE TITLE
WTF widget control widget

### ISSUE THREAD

**Issue by E3V3A** [wtfutil/wtf#372]
I'd like to have a ~~Control widget~~ *root-level overlay* that only lists the modules and where you can enable/disbale them by klicking `[y,n]` or space to toggle. The widget would directly edit the `enabled: true` in the `config.yml`, so changes would be made instantly!

```text
Widget:    Enabled?
----------------------
security   [x]
weather    [ ]
status     [ ]
awesome    [x]
```

**Comment by anandsudhir** [comment]
Interesting idea. Any thoughts on one could control the location of the widget itself?

**Comment by senorprogrammer** [comment]
I could see this being a root-level overlay. Press Ctrl-something when not focused on a specific widget to bring up a modal perhaps?

**Comment by anandsudhir** [comment]
Nice! I like the modal idea better actually. Less intrusive and the "Co trol widget" doesn't eat up screen space

**Comment by E3V3A** [comment]
Great points there!
