### ISSUE TITLE
Consider moving module/widget directories from / (root) to new /modules dir?

### ISSUE THREAD

**Issue by E3V3A** [wtfutil/wtf#375]
Seeing how the popularity of WTF is creating new modules every week, it might be good to put all the module directories in it own `modules` direcotry. (It would make the front page of Github more readable as well.)

What are your thoughts?

**Comment by senorprogrammer** [comment]
Apologies for the delay on this. I completely agree with your suggestion. It would definitely clean things up and make the code structure more similar to the documentation structure, which would be excellent.

**Comment by senorprogrammer** [comment]
Done https://github.com/wtfutil/wtf/pull/392
