### ISSUE TITLE
make install fails due to Makefile bug

### ISSUE THREAD

**Issue by E3V3A** [wtfutil/wtf#378]
**Problem**: 

Running `make install` fails because since *wtf* has either not been installed in the `$HOME/go/bin` path, or your PATH does not include it, the `which wtf` command fails. This is just an annoyance and nothing serious. 

```bash
$ make install
go clean
go install -ldflags="-s -w -X main.version=0.5.0-13-g3122f2 -X main.date=2019-02-11T00:01:21+0200"
which wtf
Makefile:26: recipe for target 'install' failed
make: *** [install] Error 1
```

**Solution**: 
I suggest to remove the last (offending) line.

**Comment by anandsudhir** [comment]
Perhaps we could log a warning that the `wtf` isn't on the `PATH` instead of failing?
