### ISSUE TITLE
Need timezone in Google Calendar widget

### ISSUE THREAD

**Issue by audioboxer217** [wtfutil/wtf#382]
#### What's the problem?
The "Family" calendar in Google Calendar is hard-coded to UTC timezone and cannot be changed.  It depends on the client's Timezone to convert appropriately.  Since WTF doesn't have a timezone it assumes the same UTC and thus all my times for my Family calendar appear incorrect.

#### How did you expect it to behave?
I would expect it to convert the timezone appropriately.  Ideally, it would use the system's timezone but I'm perfectly fine with this just being a setting in the config.

#### Operating system 
OS X Mojave (10.14.2)
Ubuntu 18.10

#### Terminal program & version
iTerm
Terminal (default in OS X)
Terminal (default in Ubuntu)

#### WTF version
0.4.0

**Comment by audioboxer217** [comment]
Screenshot as an example.  Notice "Gymnastics Practice" is at 16:00 my local time (US Central) which shows in Google Calendar but WTF is showing 22:00 which is the UTC equivalent.
In WTF:
<img src="https://user-images.githubusercontent.com/6342499/52588534-4ee5b500-2e02-11e9-83f1-d6c991583447.png" width="400" height="600">

In Google Calendar:
![image](https://user-images.githubusercontent.com/6342499/52588650-92402380-2e02-11e9-9aba-3d604465b198.png)

**Comment by senorprogrammer** [comment]
Fixed by @jeangovil in https://github.com/wtfutil/wtf/pull/490
