### ISSUE TITLE
Could you create a telegram group for users to talk?

### ISSUE THREAD

**Issue by tabris233** [wtfutil/wtf#385]
Could you create a telegram or gitter group for users to talk?

**(sorry for my poor english)**

**Comment by anandsudhir** [comment]
We already have Gitter or this. https://gitter.im/wtfutil/Lobby.
Maybe that could work?

**Comment by E3V3A** [comment]
@anandsudhir 
We should put this in the front README if not already there!

**Comment by anandsudhir** [comment]
Its already on the README as a badge. But, I guess its not that noticeable after all.
We could add it again as a link or contact section perhaps? Thoughts?

**Comment by senorprogrammer** [comment]
Closed because we have Gitter
