### ISSUE TITLE
Go modules

### ISSUE THREAD

**Issue by retgits** [wtfutil/wtf#406]
@senorprogrammer, is **wtf** looking at moving to Go modules? If so, I'd love to help out make the move 😄

**Comment by senorprogrammer** [comment]
Yes, absolutely. Before that I want to ensure that creating a module is much easier than it is now, and has less (ideally no) dependencies on the underlying platform used for display (tcell, etc.). This branch is currently in progress to move in that direction: https://github.com/wtfutil/wtf/pull/402

Do you have thoughts about how modules would look for wtf?

**Comment by retgits** [comment]
I think that [Go modules](https://github.com/golang/go/wiki/Modules) and modules for WTF are slightly different, but could be closely related. 

For Go modules specifically, it would allow WTF to remove the vendor directory and replace the `Gopkg.*` files with `go.mod` and `go.sum`. Especially with Go 1.12, the support for modules is really where it should be in terms of dependency management. It could/should also speed up the build process quite a bit.

**Comment by senorprogrammer** [comment]
Right, I was conflating the two. Having Go modules is definitely the direction it should go. I would love to see the `vendor` directory go away.

**Comment by retgits** [comment]
Awesome! Would you mind if I take a stab at it? If so, is there a particular branch you want me to work off?

**Comment by senorprogrammer** [comment]
Go for it. Create a new branch off master and you're good.

**Comment by retgits** [comment]
Just created a PR for it 😄(#417)  I know the PR description is a bit on the long side, but I wanted to thoroughly document the changes I made to make your review easier.

**Comment by senorprogrammer** [comment]
Closed from https://github.com/wtfutil/wtf/pull/417
