### ISSUE TITLE
Add RSS feed reader

### ISSUE THREAD

**Issue by senorprogrammer** [wtfutil/wtf#42]

**Comment by senorprogrammer** [comment]
Nah.

**Comment by robertmain** [comment]
This would actually be pretty nice to have for things that aren't natively supported (for example the status of the subway), so I can see subway delays etc. on my dashboard...

**Comment by Seanstoppable** [comment]
@robertmain do you have an example of something showing subway delays via RSS? I want to see if I can do something reasonable with cmdrunner and an external script as an example of how to leverage that more.

**Comment by robertmain** [comment]
Hmm. I could've sworn that @mbta had RSS feeds published, but it would appear not

**Comment by senorprogrammer** [comment]
Added with https://github.com/wtfutil/wtf/pull/486
