### ISSUE TITLE
Will wtfutil support rgba color in the future?

### ISSUE THREAD

**Issue by tabris233** [wtfutil/wtf#421]
#### What problem does this solve?
Wtfutil doesn't support RGBA now.

#### How do envision it working?

Wtfutil is on the left,  wish it to achieve a transparency similar to the right.

![深度截图_选择区域_20190428182750](https://user-images.githubusercontent.com/29500388/56863002-6f75e200-69e3-11e9-82ac-0c7d89326b58.png)

**Comment by senorprogrammer** [comment]
Interesting idea. That would likely need to fall through to a lower level - probably down to https://github.com/gdamore/tcell. It's entirely possible that already supports it, I haven't checked.

**Comment by Seanstoppable** [comment]
@tabris233 We recently improved transparency. Can you take it for another spin?

**Comment by guilatrova** [comment]
@Seanstoppable How can I test out the transparency?

**Comment by senorprogrammer** [comment]
In your config file, comment out the `wtf.colors.background` settings (it's probably `black` by default). Restart `wtf` and if your terminal supports transparency and has it enabled, you should see it.

**Comment by guilatrova** [comment]
@senorprogrammer Is it the latest release already? Because mine terminal still defaults to `black`.

**Comment by senorprogrammer** [comment]
Ah, no. That's currently only in `master`. But there will be a new release some time this week that will include it.

**Comment by senorprogrammer** [comment]
v0.21.0 has been released with these fixes.
