### ISSUE TITLE
Selectable windows are not deterministic

### ISSUE THREAD

**Issue by Seanstoppable** [wtfutil/wtf#435]
#### What's the problem?

Windows that are selectable from the number row do not get the same numbers consistently

#### How did you expect it to behave?

That these be consistent in some way. Either order from config (since backed by a map, this is likely why they are random), alphabetical, sorted by order from the top left corner. Anything really!

#### Operating system 

OSX

#### Terminal program & version

iterm2

#### WTF version

master

**Comment by senorprogrammer** [comment]
Yep. In the meantime the hack to work around this is to explicitly assign a number for each in the config, using `focusChar: n` where n is the number to bind.

**Comment by senorprogrammer** [comment]
Closed by https://github.com/wtfutil/wtf/pull/440
