### ISSUE TITLE
Standardize some of the keyboard items

### ISSUE THREAD

**Issue by Seanstoppable** [wtfutil/wtf#445]
Not all keyboard widgets have the same controls where they could
In particular, I think everything should support `Unselect` to clear selections, and either all of them should support refresh, or none of them should support refresh

**Comment by senorprogrammer** [comment]
Agreed. And I think they should all support `Refresh`. It's nice to be able to force a data update outside the scheduled interval.

**Comment by senorprogrammer** [comment]
Closing this as satisfied by https://github.com/wtfutil/wtf/pull/459

If that's not correct, comment here and I'll reopen.
