### ISSUE TITLE
Trello - Multi list fails

### ISSUE THREAD

**Issue by paoloantinori** [wtfutil/wtf#454]
#### What's the problem?
Support for multi-list is not working. Nothing is displayed when an array of boards is passed to the configuration

Config used: `list:  ["Todo", "In Progress"]`, while it works using `      list:  "In Progress"`

#### How did you expect it to behave?
Display some content

#### Operating system 
Linux 64bit

#### Terminal program & version
terminator-1.91-9.fc30.noarch

#### WTF version
`0.10.0`

**Comment by senorprogrammer** [comment]
This issue has been fixed and will be available in the next release.

**Comment by senorprogrammer** [comment]
v0.10.1 is now available. Fixes this issue: https://github.com/wtfutil/wtf/releases/tag/v0.10.1
