### ISSUE TITLE
Allow multiple applications to be monitored in NewRelic

### ISSUE THREAD

**Issue by ChrisDBrown** [wtfutil/wtf#471]
#### What problem does this solve?
Currently only one applications deploys can be tracked, where most users of NewRelic will have multiple.

#### How do envision it working?
Similar to other widgets this should allow for multiple "pages" to be tabbed through, one per application registered. Config would be updated to allow an array of application IDs rather than a single value.

EDIT: Meant to add - my knowledge of golang is very minimal, but I'm happy to try and tackle this if the feature is generally agreed upon.

**Comment by senorprogrammer** [comment]
I think this would be a great addition. If you want to have a go at  it, please do. If you need help feel free to ask on this issue or in the Slack channel.

**Comment by senorprogrammer** [comment]
Added in https://github.com/wtfutil/wtf/pull/607
