### ISSUE TITLE
Feature Request - Slack status (or any other curl-able website status)

### ISSUE THREAD

**Issue by saicrazyfire** [wtfutil/wtf#476]
#### What problem does this solve?

Find the status of certain websites like Slack. I can `curl` the status by doing this:

`curl -s https://status.slack.com/api/v2.0.0/current`

#### How do envision it working?

The module should have a title field and pretty print certain JSON attributes

For Slack, the JSON response of above is:

```json
{
  "status": "ok",
  "date_created": "2019-06-21T14:00:30-07:00",
  "date_updated": "2019-06-21T14:00:30-07:00",
  "active_incidents": []
}
```

I would like the module to print the status, last checked (date_updated) and any incidents, if any

**Comment by Seanstoppable** [comment]
I thought this would be an interesting candidate for using cmdrunner, and thought I would give it a try.

By using jq, on OSX, I can create the following shell script:

`
#!/bin/sh

curl -s https://status.slack.com/api/v2.0.0/current | jq -r '"Status: " + (if (.status == "active") then "Active Incident" else "Ok" end),"Last Updated: " + .date_updated,if (.active_incidents[] | length) > 0 then "Active Incidents\n" + .active_incidents[] .title else "" end'
`

Then,adding the following to the config:

`
     slack_status:
        cmd: "slack_status_check.sh"
        enabled: true
        type: "cmdrunner"
        position:
          top: 5
          left: 0
          height: 3
          width: 4
        refreshInterval: 30
`

I get the following widget:

<img width="472" alt="Screen Shot 2019-06-26 at 10 54 44 PM" src="https://user-images.githubusercontent.com/1523955/60230958-b35f5900-9865-11e9-9c18-64223382e51d.png">

**Comment by saicrazyfire** [comment]
Wow, `jq` is really powerful; did not know you could do all that.  Very handy, thanks! And it came at the right time, Slack is currently experiencing a major outage 😱

**Comment by saicrazyfire** [comment]
Do you know if the cmdrunner type has an optional title field? I'd like to not have the filename as the title

**Comment by Seanstoppable** [comment]
We do not, but I agree with your observation. I'll work on making this possible, for friendlier titles.

**Comment by Seanstoppable** [comment]
You should now be able to set `title` for cmdrunner @saicrazyfire

**Comment by senorprogrammer** [comment]
@Seanstoppable's example has been merged into the documentation here: https://wtfutil.com/modules/cmdrunner/statuspages/
