### ISSUE TITLE
Cannot install install -ldflags="-s -w"  on mac

### ISSUE THREAD

**Issue by askemeline** [wtfutil/wtf#478]
Hello, I would like to install the project on my mac but I got an error when I did 
```go install -ldflags="-s -w"```

```
modules/github/display.go:6:2: cannot find package "github.com/google/go-github/v25/github" in any of:
        /usr/local/opt/go/libexec/src/github.com/google/go-github/v25/github (from $GOROOT)
        /Users/emeline/go/src/github.com/google/go-github/v25/github (from $GOPATH)
```

Someone know how to resolve it ? thanks a lot

**Comment by senorprogrammer** [comment]
I wonder if v25 might not be available anymore. I'm going to bump the version to v26 and see what happens.

**Comment by senorprogrammer** [comment]
Hi, I've updated `go-github` to the latest version. Could you try pulling `master` and trying `make install` again?

**Comment by askemeline** [comment]
Hi, many thanks it's working now :)

**Comment by senorprogrammer** [comment]
Awesome, thanks for posting this issue and letting me know!
