### ISSUE TITLE
Arm/RPi not working / compiling

### ISSUE THREAD

**Issue by step21** [wtfutil/wtf#493]
#### What's the problem?
Doesn't build on armv7

Error:

```
go get -u github.com/wtfutil/wtf
go: cannot find main module; see 'go help modules'
```

#### How did you expect it to behave?
To compile

#### Operating system 
Latest Raspbian

#### Terminal program & version
iTerm2 3.2.9

#### WTF version
0.13.0

**Comment by step21** [comment]
Update: it seems to work when just doing `go get github.com/wtfutil/wtf`
So no idea why you set goproxy to gocenter.io, but it seems to break things.

**Comment by senorprogrammer** [comment]
That would be the source for modules. Do you also have `export GO111MODULE=on` set?

And when you did `go get -u github.com/wtfutil/wtf` did it actually fetch the `wtf` source?

**Comment by step21** [comment]
It seemed like it did. Afterwards, I could run `wtf` and it started, though complaining about missing config file.
I cannot verfiy whether `export GO11Module=on` was set, but probably? I reran the original commands and now that worked too. (or maybe it just kept the old stuff?) Weird.

**Comment by senorprogrammer** [comment]
That's interesting. I have a Pi 4 on the way. When it arrives I'll be trying WTF on it. Hopefully that will reveal some of these issues.

**Comment by step21** [comment]
Yeah, looks niceish for now with the default config.
