### ISSUE TITLE
Is it possible to use WTF as a library?

### ISSUE THREAD

**Issue by flw-cn** [wtfutil/wtf#495]
#### What problem are you having and how can we help?

I also wrote a Text UI application with tview, which is a MUD client. I am going to use WTF to display the status of the game character, as well as other useful information for the player. Is it possible to use WTF as a library? Then I can evoke WTF with a hotkey and provide data for the controls in it?

Thank you in advance.

**Comment by senorprogrammer** [comment]
I would suspect it's probably not possible given the current design of WTF, but then again I've never actually tried to do that.

**Comment by flw-cn** [comment]
I understand. Thank you for your reply. I will try it myself.
