### ISSUE TITLE
AWS module

### ISSUE THREAD

**Issue by mehlert-zz** [wtfutil/wtf#496]
#### What problem does this solve?
Quickly review AWS info from a terminal rather than a browser

#### How do envision it working?
This would result in making a mess of YML files, but something like:
`./wtf --config=./aws/ec2/prod/web/instance.yml`

Acting as a filter on something like `aws ec2 describe-instances --instance-id i-1234567890abcdef0`

Ideally it would support a variety of filters to create layouts around then, like an arbitrary EC2 instance or some other object, and it's associated VPC, or RDS instance and it's rules. CPU or MEM metrics? EKS. Provide, shelter, feed, and nurse a pony for me.

**Comment by Seanstoppable** [comment]
This is easily doable and customizable using [jq](https://stedolan.github.io/jq/) and CmdRunner.

Example shell script:

```
aws ec2 describe-instances | jq -r '"Instance: "+(.Reservations[].Instances[].Tags[] | select(.Key=="Name").Value) +" \nState: " + .Reservations[].Instances[].State.Name'
```

Will produce output like:

```
Instance: <some contrived name>
State: running
```

The AWS CLI lets you prefilter your data/choose which services you want to query, and `jq` lets you select and format which fields you want from the results. CmdRunner will then show the results. Something similar was done for this ticket: https://github.com/wtfutil/wtf/issues/476

**Comment by l13t** [comment]
there is an amazing tool called `awless`. https://github.com/wallix/awless

**Comment by 3mard** [comment]
I'd like to take this
