### ISSUE TITLE
Input box and real-time fuzzy filtering a set of objects to display

### ISSUE THREAD

**Issue by mehlert-zz** [wtfutil/wtf#497]
#### What problem does this solve?
Run `./wtf` and change between configs in real-time

#### How do envision it working?

Something like fzf, filters the list of config files in a `config/` dir relative to the `wtf` binary location at launch. Pressing enter redraws the screen with the new configs spec

And a pony.

**Comment by senorprogrammer** [comment]
So you want to have support for multiple config files and be able to switch between them somehow?
