### ISSUE TITLE
Google Analytics module

### ISSUE THREAD

**Issue by willjohnson** [wtfutil/wtf#499]
#### What problem does this solve?

This would allow someone to see the number of visitors on their website(s) on their dashboard.

#### How do envision it working?

A user would be able to connect their dashboard to Google Analytics via the API. Inside of the wtf config they would have their API key as well as an array of Google Analytics codes for the websites as well as a label for each. The dashboard would then display:

website 1: 1001
website 2: 2001
website 3: 3001

Unique visitor counts would be for that month.

**Comment by DylanBartels** [comment]
I would love to create a pull request for this next week, would that be alright?

**Comment by senorprogrammer** [comment]
Definitely, that would be great

**Comment by DylanBartels** [comment]
Created PR for module & docs 

#506
wtfutil/wtfdocs#42

**Comment by senorprogrammer** [comment]
Added with this PR https://github.com/wtfutil/wtf/pull/506 by @DylanBartels
