### ISSUE TITLE
newrelic dependency is no longer reachable

### ISSUE THREAD

**Issue by marsam** [wtfutil/wtf#501]
#### What's the problem?
https://github.com/yfronto/newrelic dependency disappeared 

#### How did you expect it to behave?
`go mod download` fails because https://github.com/yfronto/newrelic is no longer reachable
https://github.com/wtfutil/wtf/blob/122ea31e45f31fb32a6f30c9a16ec12a68b426e7/go.mod#L42

#### WTF version
HEAD https://github.com/wtfutil/wtf/commit/122ea31e45f31fb32a6f30c9a16ec12a68b426e7

**Comment by senorprogrammer** [comment]
That is unfortunate. Going to have to think about a solution for this happening for other dependencies too. In the meantime, NewRelic support will be broken and I may remove it from the repo.

**Comment by senorprogrammer** [comment]
I just `vendor`ed all dependencies which puts NewRelic into the `vendor` directory. `go mod download` is going to still be broken but you should be able to pull the source and run `make build -mod=vendor` and get a working build with NewRelic support (I hope - I don't use NewRelic anymore so I don't know for certain that the module still works).

**Comment by Seanstoppable** [comment]
Very weird in that it isn't just the one repo, but the entire user was deleted. The individual's entire internet presence (twitter/linkedin/website/github) also seems to have gone dark recently.

**Comment by senorprogrammer** [comment]
Yeah, very strange. Given that I have the original source in `vendor`, I'll probably just roll it into the `modules/newerelic` directory alongside the app code.

**Comment by marsam** [comment]
Thanks for looking into this. Do you think is necessary to cut a release? otherwise the latest tag is broken.

**Comment by senorprogrammer** [comment]
Yep, I just put out [v0.17.0](https://github.com/wtfutil/wtf/releases/tag/v0.17.0). Thanks for catching this issue!

**Comment by senorprogrammer** [comment]
With vendoring this issue is now resolved. Thanks for reporting this!

**Comment by avdv** [comment]
Hi.

> With vendoring this issue is now resolved. Thanks for reporting this!

What's the current status on the vendoring? Do you update/maintain the vendored dependencies on a regular basis? 

Is it still needed at all, given that you can retrieve them from gocenter.io?

**Comment by senorprogrammer** [comment]
I would love to remove vendoring. It was added because versions referenced in `go.mod` were disappearing from repositories and causing builds from source to fail for people. However doing so is a manual process and having all that 'extra' code in the repo isn't ideal. If you have thoughts on how better to do this, I'd love to hear.

**Comment by avdv** [comment]
> If you have thoughts on how better to do this, I'd love to hear.

I think you'll only ever hit the problem when you forget to execute `export GOPROXY=...` as the dependency in question is still available there (probably forever?).

:bulb: I just realized @marsam is the one who reported the problem, and the one maintaining the wtf in nixpkgs. This is why I came here, because of his comment here:

https://github.com/marsam/nixpkgs/blob/52de09ce84a9a54662d3dc860711ed2b820dfb2e/pkgs/applications/misc/wtf/default.nix#L21-L28
```
  # As per https://github.com/wtfutil/wtf/issues/501, one of the
  # dependencies can't be fetched, so vendored dependencies should
  # be used instead
  modBuildPhase = ''
    runHook preBuild
    make build -mod=vendor
    runHook postBuild
  '';
```
I suppose nobody else actually hit this problem in the wild, only when building on nix, which is a bit special / more restrictive.

It seems to me that it would work setting the GOPROXY during the fetch phase of the nix build, and not use the vendor'ed dependencies at all. WDYT, @marsam?

**Comment by Seanstoppable** [comment]
On one hand, I am sure JFrog is not going to dissapear overnight, on the other the repo in question dissapeared completely. Meaning that making changes if needed becomes harder.
If we wanted to, we could probably just push a hard fork of the library to the wtfutil project, and fix all references.

**Comment by senorprogrammer** [comment]
I'll be updating to Go 1.13 soon. I haven't read the docs yet, but perhaps the new module proxy will help with this?

**Comment by marsam** [comment]
>@avdv wrote:
> It seems to me that it would work setting the GOPROXY during the fetch phase of the nix build, and not use the vendor'ed dependencies at all. WDYT, @marsam?

seems doable. Checking the official index, the module seems to be available there
```http
GET https://proxy.golang.org/github.com/yfronto/newrelic/@v/v0.0.0-20180622232530-7c9c2852e8f9.info
```
```
{
  "Version": "v0.0.0-20180622232530-7c9c2852e8f9",
  "Time": "2018-06-22T23:25:30Z"
}
```

>@Seanstoppable wrote:
>If we wanted to, we could probably just push a hard fork of the library to the wtfutil project, and fix all references.

👍 I think this is a better solution, otherwise it will fail when someone tries to build it with an empty `GOPROXY`. 
Software Heritage has a archive of the repository https://archive.softwareheritage.org/browse/origin/https://github.com/yfronto/newrelic/directory/

>@senorprogrammer wrote:
>I'll be updating to Go 1.13 soon. I haven't read the docs yet, but perhaps the new module proxy will help with this?

I think so, [by default](https://blog.golang.org/module-mirror-launch) it will use https://proxy.golang.org, and the module seems to be mirrored there.
