### ISSUE TITLE
ERROR: Could not load 'config.yml'.

### ISSUE THREAD

**Issue by TangHuaiZhe** [wtfutil/wtf#502]
#### What's the problem?
Install via brew
`brew tap wtfutil/wtfutil`
`brew install wtfutil`

get:

>  /usr/local/Cellar/wtfutil/0.16.1: 6 files, 29.1MB, built in 4 seconds

run `wtfutil` and get error:

> ERROR: Could not load 'config.yml'.
> 
> This could mean one of two things:
> 
>     1. Your config.yml file is missing. Check in ~/.config/wtf to see if config.yml is there.
>     2. Your config.yml file has a syntax error. Try running it through http://www.yamllint.com to check for errors.
> 
> Error: open /Users/tang/.config/wtf/config.yml: no such file or directory
> 

Try to confirm `config.yml` file exist or not:
`cat  ~/.config/wtf/config.yml`

> cat: /Users/tang/.config/wtf/config.yml: No such file or directory

` open   ~/.config/wtf/`
> The file /Users/tang/.config/wtf does not exist

#### How did you expect it to behave?
run `wtfutil` and work ok

#### Operating system 
macOs 10.14.5 (18F132)
#### Terminal program & version
mac terminal using oh-my-zsh
#### WTF version
0.16.1

**Comment by sfsoul** [comment]
i get same problem!!

**Comment by sfsoul** [comment]
I think I solved the problem in this way。
```
cd ~/.config
mkdir wtf
touch wtf/config.yml
```
then, enter `wtfutil`, you will can see 
<img width="753" alt="WechatIMG490" src="https://user-images.githubusercontent.com/18617129/61266051-a0390c80-a7c5-11e9-895a-fb6f5d0b15ba.png">

**Comment by TangHuaiZhe** [comment]
@sfsoul  Good, it works, use sample config file looks better.[sample config](https://github.com/wtfutil/wtf/blob/master/_sample_configs/sample_config.yml)
![image](https://user-images.githubusercontent.com/7965577/61266486-9368e880-a7c6-11e9-9207-ca45ceb8c39b.png)

**Comment by sfsoul** [comment]
@TangHuaiZhe yeah，this's great.

**Comment by senorprogrammer** [comment]
Good to know, thanks folks. Filing this as a bug.

**Comment by senorprogrammer** [comment]
Seeing this same issue installing from source on a RaspPi
