### ISSUE TITLE
Build and execute as part of the CI pipeline

### ISSUE THREAD

**Issue by senorprogrammer** [wtfutil/wtf#505]
#### What problem does this solve?

It's possible to ship breaking changes even with the existing CI because the executable could be code-valid but not runtime-valid. These kinds of bugs are thus only caught by end-users, usually people new to the project running it for the first time and lacking knowledge of how to debug a bad build.

#### How do envision it working?

As part of the CI pipeline, the system would `go get -u github.com/wtfutil/wtf`, run through the build and installation process, and run the executable. If it runs, terminate it. If it exists with any code other than `0`, fail the build.

**Comment by felicianotech** [comment]
I'll provide a PR for this in the next day or two. There's also questions I'll bring up as to how we can improve the CI process even more.
