### ISSUE TITLE
Rollbar module broken?

### ISSUE THREAD

**Issue by International** [wtfutil/wtf#507]
## What's broken?
Hello, been trying to configure the rollbar module. Nothing gets displayed, and after adding some logs, it looks like the refreshInterval parameter is not being configured.

Shouldn't the last call from widget.Refresh not be to Refresh, but perhaps widget.Render instead?

Thanks

**Comment by senorprogrammer** [comment]
Can you paste a copy of your config for Rollbar (redacting any API credentials etc. if necessary). I don't use Rollbar but might be able to help. It's also entirely possible that module is broken.

**Comment by International** [comment]
I just took the default one, and changed the accessToken, projectOwner and projectOwner. If you would like to debug it, you could change this in client.CurrentActiveItems:
```

func CurrentActiveItems(accessToken, assignedToName string, activeOnly bool) (*ActiveItems, error) {
	items := &ActiveItems{}

	rollbarAPIURL.Host = "api.rollbar.com"
	rollbarAPIURL.Path = "/api/1/items"
	//resp, err := rollbarItemRequest(accessToken, assignedToName, activeOnly)
	//if err != nil {
	//	return items, err
	//}
	//
	//parseJSON(&items, resp.Body)
	items.Results.Items = []Item{
		{Environment: "prod", Title: "show me", },
	}

	return items, nil
}
```
so that you wouldn't need to do an actual network call. It's how I was debugging also.

**Comment by Seanstoppable** [comment]
You are correct that we should be calling Render rather than having Refresh call itself. I've opened up a PR, but I don't have rollbar myself to test @International

**Comment by International** [comment]
i will verify the pr in a few hours, and update it with a comment

**Comment by senorprogrammer** [comment]
Waiting for verification before closing this issue

**Comment by International** [comment]
I can confirm it works. Thanks!
