### ISSUE TITLE
Any way to specify `config.yml` other `~/.config/wtf/config.yml` folder?

### ISSUE THREAD

**Issue by chenrui333** [wtfutil/wtf#509]
## How can we help?

I am trying to add wtf into homebrew-core (PR: https://github.com/Homebrew/homebrew-core/pull/39962), but I constantly run into the permission issue even though I try to specify the config file in this way (ignore the weird path):

```
/usr/local/Cellar/wtfutil/0.17.1/bin/wtf --config=/private/tmp/wtfutil-test-20190720-64834-1j01eaq/config.yml
```

Let me know what is the right way to do the `--config=<path>` reference.

**Comment by senorprogrammer** [comment]
Hi @chenrui333, thanks for your work on this. As of `0.15.0` the binary is called `wtfutil`, so that might be causing issues (and if the installed binary is being named `wtf`, it should be changed to `wtfutil` to not conflict with an existing utility in Homebrew).

The way you're defining the path looks correct to me. I just tried with both relative and absolute paths to be sure:
* `wtfutil --config=_sample_configs/sample_config.yml`
* `wtfutil --config=/Users/ccummer/go/src/github.com/wtfutil/wtf/_sample_configs/sample_config.yml`

What error are you getting when you try and write to `~/.config`? WTF doesn't actually try to create the `~/.config` directory if it doesn't already exist, which is definitely a bug and undoubtedly causing problems for some people.

**Comment by senorprogrammer** [comment]
I've just created https://github.com/wtfutil/wtf/issues/510 to address that bug. I should have a fix today.

**Comment by chenrui333** [comment]
Did not realize the binary got changed, that is actually even better (the formula name could be just `wtfutil`). I will wait for your fix and submit a new PR to have this utility tool in the homebrew-core.

Thanks!

**Comment by senorprogrammer** [comment]
Yeah, the homebrew conflict was the whole reason for changing it: https://wtfutil.com/blog/2019-07-10-wtfutil-release/

**Comment by chenrui333** [comment]
Good to know about the thought process of the binary name change. Honestly, I was thinking to ask before. :)

**Comment by senorprogrammer** [comment]
v0.18.0 has been released https://github.com/wtfutil/wtf/releases/tag/v0.18.0

Hopefully this helps out. Any other issues you run into or any other ways I can help, open a ticket here and I'll do so.

**Comment by chenrui333** [comment]
Sure. I am going to test it out now. Again, thanks for the quick turnaround. 💯

**Comment by chenrui333** [comment]
```
==> /usr/local/Cellar/wtfutil/0.18.0/bin/wtfutil --config=/private/tmp/wtfutil-test-20190720-75894-jpnems/config.yml

ERROR: Could not create the '~/.config/wtf/' directory.
```

Looks like still having the same issue?

**Comment by chenrui333** [comment]
Going to reopen that PR, so that easy to understand the problem.

**Comment by senorprogrammer** [comment]
Underneath that error line is should also have printed one that starts with `Error: ` and then an error message. If that line exists, can you paste it here as well?

**Comment by chenrui333** [comment]
here you go
```
$ /usr/local/Cellar/wtfutil/0.18.0/bin/wtfutil --config=/private/tmp/wtfutil-test-20190720-77521-167to3t/config.yml

ERROR: Could not load 'config.yml'.

This could mean one of two things:

    1. Your config.yml file is missing. Check in ~/.config/wtf to see if config.yml is there.
    2. Your config.yml file has a syntax error. Try running it through http://www.yamllint.com to check for errors.

Error: open /private/tmp/wtfutil-test-20190720-77521-167to3t/config.yml: no such file or directory
```

**Comment by chenrui333** [comment]
I might need to grab the latest sample config.yml, which I was still using the 0.10.3 one.

**Comment by senorprogrammer** [comment]
A few things to check:

1. You have a `~/.config` directory?
2. You have a `~/.config/wtf/` directory?
3. Does `~/.config/wtf/` contain a `config.yml` file?

That error immediately above means it can't find the specific config file you're passing it from the `tmp` dir. I definitely need to make that error message much better for cases in which explicit config files cannot be found.

**Comment by senorprogrammer** [comment]
And what happens if you just run `$ /usr/local/Cellar/wtfutil/0.18.0/bin/wtfutil` without specifying a config file?

**Comment by chenrui333** [comment]
yeah, it works for me now (yaml config file syntax issue). Trying to sort out the test step issue.

**Comment by chenrui333** [comment]
File a new PR for including it to homebrew-core. Thanks for helping with the issue.

**Comment by senorprogrammer** [comment]
Awesome. Thank you very much for making this happen.

**Comment by chenrui333** [comment]
👍 Closing the issue now.
