### ISSUE TITLE
Esc key does not dismiss modal dialog in Todo

### ISSUE THREAD

**Issue by senorprogrammer** [wtfutil/wtf#520]
The Esc key should dismiss the modal dialog in the Todo module. It no longer does.

**Comment by senorprogrammer** [comment]
Tab key should also move between fields/buttons. No longer does.

**Comment by Seanstoppable** [comment]
As far as I can tell, the top level keybindings are stopping widget level keybindings. Potentially a problem with the way I restructured some of the code. I'll try to dig in this weekend.

**Comment by Seanstoppable** [comment]
It actually has to do with this code block:
https://github.com/wtfutil/wtf/blob/master/app/wtf_app.go#L83-L95

The 'return nil' means that the key doesn't flow through to the widgets themselves.

**Comment by Seanstoppable** [comment]
Opened a PR where the behavior appears to be correct (at least for TODO). Tab doesn't cycle through when the window captures it. Esc seems to work appropriately

**Comment by senorprogrammer** [comment]
Fixed by https://github.com/wtfutil/wtf/pull/523
