### ISSUE TITLE
Debug/verbose mode? 

### ISSUE THREAD

**Issue by stenwt** [wtfutil/wtf#527]
## How can we help?

I'm attempting to use the GitHub module, pointed at a local GitHub Enterprise server. When I run wtf, I get this in the logs: 

``` 2019/08/05 11:34:40 log.go:25: [] ```

The token I created for wtf does not get used, according to my GHE server, and the GitHub module in wtf is posting empty data. 

I'd probably be able to figure this out, but I don't see any way to get more information out of either wtf in general, or the GitHub module in specific. Is there a "verbosity" setting somewhere I can increase?

**Comment by senorprogrammer** [comment]
Unfortunately there's not yet any better debugging of internal failures for modules in place. I doubt that log line is even from the GitHub module, as that module doesn't use `log`. 

First thing I would do is run your config.yml through `http://www.yamllint.com` and see what it says, to ensure the YAML structure is correct.
