### ISSUE TITLE
Jenkins job filtering by regex not preserved when selecting actual job

### ISSUE THREAD

**Issue by DimitarPetrov** [wtfutil/wtf#532]
When i specify a regex that filters the jobs shown in the Jenkins widget the visual result is as expected. Unfortunately when i try to navigate to the desired job with the arrow keys, it seems like the filtering is not preserved and even though you don't see some of them you still iterate over all existing jobs and not only the jobs matched by the regex in configuration.

**Comment by Seanstoppable** [comment]
You are correct that we are filtering jobs at view time, and this impacts selection. Want to give https://github.com/wtfutil/wtf/pull/533 a shot? I unfortunately do not have a jenkins server to test against at this time.

**Comment by DimitarPetrov** [comment]
@Seanstoppable 
Thank you for the fast response! 
I just tested it and it works fine.

**Comment by Seanstoppable** [comment]
No problem!
