### ISSUE TITLE
Generalize TODO

### ISSUE THREAD

**Issue by Seanstoppable** [wtfutil/wtf#550]
## What should it do?

Right now, we have a number of TODO integrations. Most of these look pretty similar, with the difference really being the API backend.

It might make more sense to generalize a single module, and have configurable backends, such that supporting a new TODO app is just writing the integration and mapping to the 'general' models.

**Comment by senorprogrammer** [comment]
Agreed, this is a great idea.

**Comment by senorprogrammer** [comment]
Closing as added via this PR https://github.com/wtfutil/wtf/pull/982
