### ISSUE TITLE
Order of projects in Git and GitHub modules not consistant

### ISSUE THREAD

**Issue by yelvert** [wtfutil/wtf#551]
## What's broken?
The order of the repos/projects in both the Git and GitHub modules changes every time wtfutil is restarted or the config file is reloaded.

For Git, I would expect the order of the repos to match the order of the array in the config file.
For GitHub, maybe the list of repos in the config file should be changed to an array, then display them in the module in that order.

**Comment by Seanstoppable** [comment]
@yelvert Are you using the map version of the config, or the list version for github? Maps in go do not guarantee order. I haven't seen this behavior using the list version.

For git, it looks like we are deliberately sorting alphabetically for some reason. I've opened a PR to review that behavior

**Comment by yelvert** [comment]
For git, I’m using a list, for github, a map.

**Comment by Seanstoppable** [comment]
I'd switch to list for github. With a map there is no way to guarantee the order in the config will be the same as the order we end up with.

**Comment by yelvert** [comment]
I don’t remember off hand, but there was a reason I had to use a map. I’ll try a list though, and see if that works.

**Comment by Seanstoppable** [comment]
Sounds good. If you have problems lemme know and we'll figure that part out too.

**Comment by senorprogrammer** [comment]
I've fixed the GitHub documentation to show the list ordering https://wtfutil.com/modules/github/

Between using a list for `github`, and PR #608 for `git`, repository ordering should now obey the configuration list order.
