### ISSUE TITLE
Microsoft 365 Calendar widget

### ISSUE THREAD

**Issue by yelvert** [wtfutil/wtf#552]
## What should it do?
It should look and work the same as the [Google Calendar widget](https://wtfutil.com/modules/google/gcal/)

Relevant API: https://docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0

**Comment by Seanstoppable** [comment]
Similar to work I am doing with the various TODO implementations, I'd consider making a 'calendar' widget that can use multiple backends.
With this, the backend is responsible for getting data, but the interaction/rendering is the same.
Could make it easier to then do something like iCal/CalDev integrations.

**Comment by senorprogrammer** [comment]
Agreed.
