### ISSUE TITLE
Could not load 'config.yml'

### ISSUE THREAD

**Issue by NSMyself** [wtfutil/wtf#553]
## What's broken?

I can't use this; I just tried to install wtfutil using Brew and ran into this:
```
ERROR Could not load 'config.yml'.

This could mean one of two things:

    1. That file doesn't exist.
    2. That file has a YAML syntax error. Try running it through http://www.yamllint.com to check for errors.

Error: open /Users/username/.config/wtf/config.yml: no such file or directory
```

I can confirm that this path does not exist (the `wtf` folder is not there) but brew install ran fine (as did the previous command, `brew tap`). I'm on macOS Mojave (10.14.6).

**Comment by kolten** [comment]
I ran into this issue as well, running `touch ~/.config/wtf/config.yml`did the trick.

**Comment by Blake-** [comment]
Ubuntu 18.04.3 LTS same error.

**Comment by KalobTaulien** [comment]
You need to create a `config.yml` file in `/Users/username/.config/wtf/config.yml`

I just ran into this. I put my entire config in there, because why not? 
¯\_(ツ)_/¯

**Comment by senorprogrammer** [comment]
The app should do that for you the first time you run it, with `config.yml` populated with some example modules. Seems its failing to do that for some people.

**Comment by senorprogrammer** [comment]
Confirmed that it's creating the `~/.config/wtf/` directory but not the config file.

**Comment by senorprogrammer** [comment]
This will be fixed in the next release.
