### ISSUE TITLE
Homebrew builds do not include a version

### ISSUE THREAD

**Issue by senorprogrammer** [wtfutil/wtf#557]
## What's broken?

Homebrew builds return the default `dev` for `wtfutil -v`, when they should return a valid version, ie: `v0.20.0-31-gbc80b9`. Likely the hombrew recipe is missing some ldflags.

**Comment by badrimurali** [comment]
I would like to contribute. can i work on this?

**Comment by senorprogrammer** [comment]
@badrimurali That would be great, thanks. The `homebrew-core` formula is here: https://github.com/Homebrew/homebrew-core/blob/master/Formula/wtfutil.rb

The Makefile contains an `install` option that uses the correct `ldflags` here: https://github.com/wtfutil/wtf/blob/master/Makefile#L36

**Comment by badrimurali** [comment]
cool. is there any documentation that i can follow to setup repo locally?

**Comment by jottr** [comment]
@senorprogrammer see merged PR above.

**Comment by senorprogrammer** [comment]
Thanks @jottr !
