### ISSUE TITLE
Feedreader module lines are too long

### ISSUE THREAD

**Issue by hxw** [wtfutil/wtf#560]
## What's broken?
The latest master modules/feedreader lines re too long by what looks like 4 characters, which causes alternate blank lines.

The problem seems to be with modules/feedreader/widget.go

there is code that formats the item title with a number, but then passes the the non-numbered title to the
utils.HighlightableHelper.

If I make this change, it works:
~~~
diff --git a/modules/feedreader/widget.go b/modules/feedreader/widget.go
index 164ee9db..97b02a46 100644
--- a/modules/feedreader/widget.go
+++ b/modules/feedreader/widget.go
@@ -151,7 +151,7 @@ func (widget *Widget) content() (string, string, bool) {
                        feedItem.item.Title,
                )
 
-               str += utils.HighlightableHelper(widget.View, row, idx, len(feedItem.item.Title))
+               str += utils.HighlightableHelper(widget.View, row, idx, len(feedItem.item.Title)+5)
        }
 
        return title, str, true
~~~

However this is not the right fix as I am not understanding the code well at present and unsure why +5 since the number format is "%2d. "  (= 4 characters).

If have time tomorrow will investigate further as I am not sure if ` RowPadding(offset, w+1)` in utils.HighlightableHelper is the problem yet.

**Comment by senorprogrammer** [comment]
A bunch of changes to how rendering is handled were recently made and in this case the widget's line wrap value was set to `true` instead of `false`. https://github.com/wtfutil/wtf/pull/563 will fix it.
