### ISSUE TITLE
Add GitLab CI module

### ISSUE THREAD

**Issue by thommor** [wtfutil/wtf#561]
## What should it do?
Add a module that given a list of projects will monitor those projects for running pipelines and jobs.

Something similar to https://github.com/timoschwarzer/gitlab-monitor

**Comment by negasus** [comment]
I made a module for myself. I can make PR for review)

[Screenshot](https://yadi.sk/i/eGSpyezcxAMR0w)

**Comment by franga2000** [comment]
Hi @negasus! Do you still have the code from that screenshot? I'd love to have a widget like this too and if you've already implemented it, there's no use in me making it from scratch.

**Comment by negasus** [comment]
> Hi @negasus! Do you still have the code from that screenshot? I'd love to have a widget like this too and if you've already implemented it, there's no use in me making it from scratch. 

Hi! No, unfortunately this code not preserved (
