### ISSUE TITLE
Does not start - error: infocmp not found

### ISSUE THREAD

**Issue by avdv** [wtfutil/wtf#562]
## What's broken?

Trying to run wtfutil (version 0.20.0) errors out with:
```console
$ wtfutil
ERROR exec: "infocmp": executable file not found in $PATH
```
I am using `termite` as a terminal, `TERM` is set to `termite`.

OS: NixOS

**Comment by senorprogrammer** [comment]
The underlying framework uses `infocmp` to figure out terminal capabilities. What happens if you `which infocmp` on your machine?

**Comment by senorprogrammer** [comment]
You might try also explicitly setting your terminal to something not `termite`. A complete list of explicitly-supported terminal definitions can be found here: https://github.com/gdamore/tcell/tree/ca8fb5bcc94b37b52eb8508d3ed8753e4762e83f/terminfo

In your config you'd define `term: xterm` for instance. See "term" here https://wtfutil.com/configuration/global_settings/.

**Comment by senorprogrammer** [comment]
Just noticed that there's a `xterm-termite` definition. That might work?

**Comment by avdv** [comment]
Thanks, using `TERM=xterm-termite wtfutil` works!

But why is there a difference? "termite" should be the correct termcap entry.

**Comment by senorprogrammer** [comment]
Not sure, you'd have to ask over on [tcell](https://github.com/gdamore/tcell/).

**Comment by avdv** [comment]
> Not sure, you'd have to ask over on [tcell](https://github.com/gdamore/tcell/).

@senorprogrammer I think they fixed it in version 1.2.0. wtf is still using 1.1.4, right?!

**Comment by senorprogrammer** [comment]
I've created PR to upgrade those dependencies. Should be in the next release https://github.com/wtfutil/wtf/pull/595

**Comment by avdv** [comment]
> I've created this PR to upgrade those dependencies. Should be in the next release #595

Perfect, thanks!

**Comment by senorprogrammer** [comment]
That branch has been merged to `master`. If you're building from source, give it a try and let me know how it goes.

**Comment by avdv** [comment]
> That branch has been merged to `master`. If you're building from source, give it a try and let me know how it goes.

It still tries to call `infocmp`. :cry: 

I was probably misinterpreting the changes [here](https://github.com/gdamore/tcell/commit/1922b3786eaefecbba6fd8e11dbfd3531fad7a54#diff-e4713edd220ab6844ec6056e261b9ef8L8), where they changed the name from `xterm-termite` to `termite`:
```diff
 	// VTE-based terminal
-	AddTerminfo(&Terminfo{
-		Name:            "xterm-termite",
+	terminfo.AddTerminfo(&terminfo.Terminfo{
+		Name:            "termite",
```
Seems like the name does not link directly to the `TERM` variable.

**Comment by avdv** [comment]
Wait a second, looking into `vendor/github.com/gdamore/tcell`, I still have the old file, with `xterm-termite` in it...

**Comment by avdv** [comment]
Actually, the problem got worse. Now it also does not work for `TERM=xterm-termite` anymore.

**Comment by avdv** [comment]
:tada: I found out how to fix it:
```diff
index bf301094..b296a9f0 100644
--- a/app/wtf_app.go
+++ b/app/wtf_app.go
@@ -4,6 +4,7 @@ import (
 	"log"
 	"time"
 
+	_ "github.com/gdamore/tcell/terminfo/extended"
 	"github.com/gdamore/tcell"
 	"github.com/olebedev/config"
 	"github.com/radovskyb/watcher"
```

**Comment by senorprogrammer** [comment]
Thanks very much for researching this. That change has been merged into `master`.
