### ISSUE TITLE
Add pages to main view

### ISSUE THREAD

**Issue by Bradley-Cooley** [wtfutil/wtf#567]
There are many widgets available that I want to use, but I am running out of space. A main window command to switch between different views would be a nice feature. The position config for each element could be turned into an array of maps from screen number to the element's position on that screen.

**Comment by senorprogrammer** [comment]
Right now the work-around is to use terminal tabs, or multiple terminals and explicitly pass different configs to different instances of wtf, as described here: https://wtfutil.com/configuration/

We do want to add the ability to switch layouts at some point. Still working out what that might look like.
