### ISSUE TITLE
Full-screen layout doesn't quite work as it should

### ISSUE THREAD

**Issue by NSMyself** [wtfutil/wtf#573]
## What's broken?

In macOS Mojave, the layout isn't displaying correctly when in fullscreen. Here's a screenshot I took when running wtfutil in iTerm (Zsh).

<img width="1792" alt="Screenshot 2019-08-30 at 10 31 43" src="https://user-images.githubusercontent.com/3126462/64010519-da5e3380-cb11-11e9-9457-2434eba0e253.png">

**Comment by v-braun** [comment]
Hey @NSMyself, I have the same issue when I tried wtfutil the first time a few days ago. Maybe this is a new bug in the current version of [tview](https://github.com/rivo/tview).

I tried different cell layouts and find out that not specifying a grid works best for me. My current config looks like this:

``` yaml
  grid:
    # How _wide_ the columns are, in terminal characters. In this case we have
    # four columns, each of which are 35 characters wide.
    # columns: [50, ]
    # How _high_ the rows are, in terminal lines. In this case we have four rows
    # that support ten line of text and one of four.
    # rows: [50]
```

As long I not define column and rows it looks good in fullscreen for me.

**Comment by NSMyself** [comment]
Awesome @v-braun! Thanks for this

**Comment by senorprogrammer** [comment]
In that case it dynamically expands all widgets to equally fill the available screen space. Which is a good solution.

**Comment by webdog** [comment]
Perhaps this changed, I had to remove the entire `grid:` block from root-level of the yaml config, rather thank leaving `grid:` section empty, with the key still present as shown above.

Errors:
```yaml
  grid:
    # How _wide_ the columns are, in terminal characters. In this case we have
    # four columns, each of which are 35 characters wide.
    #columns: [35, 35, 35, 35]
    # How _high_ the rows are, in terminal lines. In this case we have four rows
    # that support ten line of text and one of four.
    #rows: [10, 10, 10, 10, 4]
```

```shell
ERROR 'grid' config values are invalid. 'columns' and 'rows' cannot be empty.

This is invalid:

  grid:
    columns: []
    rows: []
```

Works:

```yaml
  #grid:
    # How _wide_ the columns are, in terminal characters. In this case we have
    # four columns, each of which are 35 characters wide.
    #columns: [35, 35, 35, 35]
    # How _high_ the rows are, in terminal lines. In this case we have four rows
    # that support ten line of text and one of four.
    #rows: [10, 10, 10, 10, 4]
```
