### ISSUE TITLE
cmdrunner should maintain color of output

### ISSUE THREAD

**Issue by MitchLillie** [wtfutil/wtf#577]
## What's broken?

`cmdrunner` seems to be blowing away the color schemes of the outputs of many programs. 

## Reproduce

1. Choose a terminal program that outputs colored text. Example: `yarn info` or `jira issues ls` (from https://github.com/keepcosmos/terjira)
2. Create a new cmdrunner module and call the script.
3. All colors are lost.

System Version: macOS 10.14.5 (18F132)
Kernel Version: Darwin 18.6.0
GNU bash, version 5.0.2(1)-release (x86_64-apple-darwin18.2.0)

**Comment by cjwelborn** [comment]
I haven't looked at this project, but a lot of programs disable their colored output if stdout is not a tty. You'd probably have to tell the command to use colors, with whatever argument is appropriate for the command (`--color=always`, `--force-color`, etc.).

**Comment by MitchLillie** [comment]
Gotcha. Yeah sadly looks like they don't have that option so I'll fiddle with `script` to try to force colorized output. Still, it would be a nice touch if there were some support for this baked in to cmdrunner.

**Comment by Seanstoppable** [comment]
I think there are some golang projects that act as TTYs that may help. I haven't done a lot of research yet, but I found https://github.com/creack/pty

**Comment by cjwelborn** [comment]
That would be a cool solution. For now, at least for the `yarn` case, check this [issue](https://github.com/yarnpkg/yarn/issues/5733#issuecomment-434330747) out. This person claims that `--color=always` works for `yarn 1.9.4`.
