### ISSUE TITLE
Docker Module

### ISSUE THREAD

**Issue by v-braun** [wtfutil/wtf#594]
Would be great to have a (or two separate) docker modules. 

The one I'm thinking if would show container states (running / stopped / restarting).
The other could display general docker information like space usage, version, container and image count (see [docker system command](https://docs.docker.com/engine/reference/commandline/system/))

**Comment by v-braun** [comment]
I opened this issue for documentation reasons. I'm currently working on this module.

**Comment by senorprogrammer** [comment]
https://github.com/wtfutil/wtf/pull/596 has been merged into `master`. Nice work @v-braun.
