### ISSUE TITLE
Long-running executable cmdrunner

### ISSUE THREAD

**Issue by cakenggt** [wtfutil/wtf#601]
## What should it do?

It might be nice to have an executable, long running version of cmdrunner that would continuously pipe it's output to the view. I imagine it would exist as a panel where you put long-running commands that you commonly run, like starting up a proxy server or something, and which could be triggered or halted by pressing `enter` on the panel.

The current cmdrunner doesn't satisfy this because it automatically reruns the command and also waits for it to stop outputting text. This would differ in that it continuously pipes the output and is only executed when the user manually executes it.

**Comment by noxer** [comment]
This partially fixed by #680.
