### ISSUE TITLE
gcal highlights not working

### ISSUE THREAD

**Issue by alecdotico** [wtfutil/wtf#611]
## What's broken?
Google Calendar color highlights don't apply. I've tried different regex combinations and I can only get the `colors.title` or `colors.past` colors applied.

## Suggestion
Maybe there is a typo on [this line](https://github.com/wtfutil/wtf/blob/v0.21.0/modules/gcal/display.go#L169)? Instead of 
`widget.settings.highlights`
Shouldn't it be
`widget.settings.colors.highlights`
?

Wtfutil version: 0.21.0 (binary)
OS: Ubuntu 18.04.3 LTS 
Linux version 4.15.0-60-generic (buildd@lgw01-amd64-030) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1))

**Comment by senorprogrammer** [comment]
That is definitely not currently working. Thanks for reporting this.
