### ISSUE TITLE
Light Theme support 

### ISSUE THREAD

**Issue by jnduli** [wtfutil/wtf#628]
I just started using wtfutil. However, the default config doesn't work well with light themes e.g. gruvbox or solarized-light. I've attached an image of how this looks: 

![Screenshot2019-09-1211:30:43](https://user-images.githubusercontent.com/19635979/64767712-d938f780-d550-11e9-92fb-1199fc58af85.png)

I haven't found any sample configs that deal with this so far, and assumed that the colors should change somehow based on the theme. Are there any docs on this?

**Comment by DoomHammer** [comment]
@jnduli have you found a solution for light themes?
