### ISSUE TITLE
Todo has a race condition when loading/saving its file

### ISSUE THREAD

**Issue by senorprogrammer** [wtfutil/wtf#637]
## What's broken?

TODO, which is loading and saving a file. I don't have a clear idea on how to handle this with the existing strategy of showing the error in the window.

**Comment by noxer** [comment]
Do you mean that `Refresh()` might be called while `persist()` is running?

**Comment by senorprogrammer** [comment]
Yep, I suspect that's probably It.

**Comment by senorprogrammer** [comment]
Pretty sure this is fixed. Haven't seen this race in awhile.
