### ISSUE TITLE
todoist not being able to parse timestamp

### ISSUE THREAD

**Issue by massa1240** [wtfutil/wtf#645]
## What's broken?

Todoist shows messsage `parsing time "2019-09-30T14:00:00Z" as "2006-01-02T15:04:05+00:00": cannot parse "Z" as "+00:00"` for tasks that were imported from GCal.

I have created a new account in todoist and synchronised my todoist with GCal. Since my tasks were first created in GCal, they got exported to todoist and now my wtfutil mod shows that message and cannot display any of the tasks.

Edit:
Apparently any task I create in todoist with time, regardless if it's floating time or timezoned, it gives me the same error

**Comment by senorprogrammer** [comment]
Confirmed. Attaching a date works fine. Attaching a time causes the error.

**Comment by massa1240** [comment]
Is there any plan to start working on a fix for this? If not, I will submit a PR if that's ok :)

**Comment by senorprogrammer** [comment]
It's all yours, please do. The code in question is over here: https://github.com/wtfutil/todoist/blob/97395e581a76cbb647a0c7b26debebc0456a6f44/todoist.go#L59

I think we'll want to support both the existing format and the affected format.

**Comment by massa1240** [comment]
Here we go :)
#hacktoberfest
https://github.com/wtfutil/todoist/pull/1

**Comment by senorprogrammer** [comment]
Fixed by https://github.com/wtfutil/todoist/pull/1
