### ISSUE TITLE
Apple Calendar Integration

### ISSUE THREAD

**Issue by TMschar** [wtfutil/wtf#651]
## What should it do?

Similar to the Google Analytics extension, it would be great with integration with Apple Calendar and iCloud Calendar so those events can be seen as well on the wtf dashboard.

## Ways to possibly approach it

If iCloud Calendar has a HTTP API, that could be leveraged or a more elegant approach could maybe be leveraging any API that macOS leverages for Calendar instead.

**Comment by senorprogrammer** [comment]
Related to https://github.com/wtfutil/wtf/issues/552
