### ISSUE TITLE
Spotify: support theming

### ISSUE THREAD

**Issue by kusold** [wtfutil/wtf#659]
## What should it do?
Currently there is no way to re-theme Spotify. It would be nice if this was configurable.
https://github.com/wtfutil/wtf/blob/f5e80119064b9f45e0703da31bfecbbeab9b0b1e/modules/spotify/widget.go#L67-L70

## Screenshot
![image](https://user-images.githubusercontent.com/509966/65647015-6309ab80-dfba-11e9-9f23-3ef3705e6d2b.png)

**Comment by senorprogrammer** [comment]
Added by https://github.com/wtfutil/wtf/pull/677
