### ISSUE TITLE
Support for out-of-tree custom modules

### ISSUE THREAD

**Issue by kBite** [wtfutil/wtf#663]
We're using an internal ticket system. Commiting a module to query it's API will necessarily expose internal information.

I think https://wtfutil.com/configuration/generate-module/ does not state all prerequisites about how to write _and_ add a new module.

Looking at `modules/` and `app/widget_maker.go` suggests modules must be

1. written in Go,
1. accessible from GitHub at compile time, and ...
1. ... included in `widget_maker.go`

Is this correct? If yes, writing an out-of-tree custom module for internal use only seems not supported yet.

As I'm new to Go, I can't estimate how difficult it would be to implement support for modules which are a) not included in `wtfutil/wtf` and b) not written in Go (optional).

What do you think about this? Could something like this be desirable for future versions of `wtf`? And how difficult could this be?

**Comment by senorprogrammer** [comment]
Right now this isn’t possible because Go does not support cross-platform dynamically-loadable modules. 

The most solution for you is probably to fork this project to a private repo and implement your module there.

**Comment by Seanstoppable** [comment]
If you are ok with only viewing information (no interaction), CmdRunner allows you to effectively wrap anything and display the information in wtfutil as well. 

I.e. you could write a python/ruby/go/java app that calls the API and displays the info as you want and have CmdRunner call it.

**Comment by kBite** [comment]
Wow, that was fast :) Thanks for your feedback

`CmdRunner` would be an option, but some interaction would be nice, too.

> Right now this isn’t possible because Go does not support cross-platform dynamically-loadable modules.

And what about dynamically-loadable modules written in Go? I mean, I don't know any Go, but for this I would learn some :D

**Comment by senorprogrammer** [comment]
Go does have a ‘plugin’ package, but that’s only supported on Linux and most Unix-compatible systems. We don’t use it because while WTF does not explicitly support other OSes yet (i.e. Windows), we also don’t want to do anything that would exclude them.

**Comment by kBite** [comment]
I'll try implementing my widget as a feedreader. This might work plug-n-play as it's just reading a XML file.

> we also don’t want to do anything that would exclude them
That seems fair. Regarding out-of-tree modules this means you won't support this feature in the near or long-term future, right? If so, this issue can be closed.

Thanks again for your feedback :)

**Comment by senorprogrammer** [comment]
Dynamically-loaded modules is something that needs to be supported at some point, especially as the number of modules grows but right now it's not particularly feasible or all that important. One day hopefully.
