### ISSUE TITLE
Fork tview, incorporate changes

### ISSUE THREAD

**Issue by senorprogrammer** [wtfutil/wtf#688]
## What should it do?

To fix [this issue](https://github.com/wtfutil/wtf/issues/618) we need this [tview PR](https://github.com/rivo/tview/pull/347) merged. It doesn't look like PRs have been merged into tview since May 2019 so we should probably fork and fix here and go back to the main repo when it catches up.

(There are also a couple other open PRs that would be useful:
* https://github.com/rivo/tview/pull/292
* https://github.com/rivo/tview/pull/296

)

**Comment by tslocum** [comment]
Just in case you're interested, I've forked tview as [cview](https://git.sr.ht/~tslocum/cview) which includes the pull requests noted above.  (I found this issue while reviewing tview's pull requests.)

**Comment by senorprogrammer** [comment]
* https://github.com/rivo/tview/pull/292 merged into view
* https://github.com/rivo/tview/pull/296 fixed with https://github.com/rivo/tview/blob/master/util.go#L125
