### ISSUE TITLE
XDG_CONFIG_HOME Should Be Used When Available

### ISSUE THREAD

**Issue by felicianotech** [wtfutil/wtf#699]
The environment variable `XDG_CONFIG_HOME` should be used when available as mentioned in the Free Desktop specification: https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

I see close mentions of this in the source code right now but it's not actually implemented.

I can work on this if it's agreed that this should be worked on.

**Comment by senorprogrammer** [comment]
Agreed. This would be an excellent improvement.

**Comment by OJFord** [comment]
Note that the docs currently still say just 'looks in .config/wtf':
https://wtfutil.com/configuration/

The value of mine does happen to be `~/.config` (it's just not worth the hassle of dealing with not only `$HOME` polluters, but '`~/.config` is the same thing, right?' tools too IMO) but it'd be good to make it clear that the env var is respected.
