### ISSUE TITLE
ToDo is not scrollable  

### ISSUE THREAD

**Issue by 3mard** [wtfutil/wtf#707]
## What's broken?

The scrolling on the todo is a bit awkward ,  and the items at the bottom of the list are not reachable 

![bug](https://user-images.githubusercontent.com/42009880/67153220-7839d780-f2e5-11e9-8840-2f029eec16de.gif)

**Comment by 3mard** [comment]
If this is indeed a bug, I'd like to take a shot at it.

**Comment by senorprogrammer** [comment]
This is definitely a bug

**Comment by 3mard** [comment]
I am on it!
