### ISSUE TITLE
Rendering of clock

### ISSUE THREAD

**Issue by daugustin** [wtfutil/wtf#711]
## What's broken?

I installed wtfutil on raspbian (from source). Everything seems fine, although the clock doesnt render correctly. It looks like this in the framebuffer, on gnome-terminal and on xterm. The rendered "[ ]" show up on both supported fonts of the widget.

![clock](https://user-images.githubusercontent.com/4355776/67226837-37050d00-f436-11e9-8e7d-d7e7eae44b7e.png)

It does not look like the image on the homepage:

![clock](https://wtfutil.com/imgs/modules/digitalclock.png)

Is this something raspbian is missing? Some font? Thanks for any feedback what could be wrong.

**Comment by senorprogrammer** [comment]
Wouldn't be missing fonts, the glyphs are defined here: https://github.com/wtfutil/wtf/blob/master/modules/digitalclock/fonts.go

Not quite sure yet.

**Comment by art1415926535** [comment]
I found out that the missing `color` in the yml file is the reason for the strange clock output.
