### ISSUE TITLE
Toggl integration

### ISSUE THREAD

**Issue by StanczakDominik** [wtfutil/wtf#725]
Hi! I wish I could contribute a straight up PR instead of bothering you with feature requests, but I'm afraid Go is a foreign language to me :(

I really enjoy using `wtf`, but I think it could do with https://toggl.com/ integration!

## What should it do?

Basically send a GET request as described [here](https://github.com/toggl/toggl_api_docs/blob/master/chapters/time_entries.md#get-running-time-entry), in other words, imitate this curl call:

```
curl -v -u 1971800d4d82861d8f2c1651fea4d212:api_token \
-X GET https://www.toggl.com/api/v8/time_entries/current
```

where `1971800d4d82861d8f2c1651fea4d212` is the actual API token supplied by the user (copying the example from the docs).

Then (the following is my idea for the look and feel):

If the "data" field of the output is `null`, display something like "There is no time entry currently being tracked!".

Otherwise, if the "data" field is a dictionary with no "description" field:

> Currently tracking a time entry since 2019-10-27T18:21:51+00:00, for 6m:30s.

Where the start date is in `output['data']['start']` and the way to get the duration is described at https://github.com/toggl/toggl_api_docs/blob/master/chapters/time_entries.md#time-entries.

Otherwise, if the description field is non-empty:

> Currently tracking "{description}" since 2019-10-27T18:21:51+00:00, for 6m:30s.

And that's about it, really!

**Comment by cori** [comment]
I have a small module that _might_ address at least in part this that I could send a PR in for, but in the spirit of _Talk, then code_ I figured I'd mention it before sending anything in.

In terms of approach it operates more or less the same as several other modules that retrieve and display a list of API entities. But I'm sure it's terribly un `go`-like.
