### ISSUE TITLE
How to configure docker ?

### ISSUE THREAD

**Issue by BartoszCoyote** [wtfutil/wtf#727]
## How can we help?

I used a custom configuration from https://wtfutil.com/modules/docker/

My docker demon up and running and i see this error.

Widget docker and/or type docker does not exist

**Comment by BartoszCoyote** [comment]
Same problem with subreddit.

Widget subreddit and/or type subreddit does not exist

**Comment by senorprogrammer** [comment]
Sounds like you have an old version installed. If you installed via `homebrew`, do this:
```
   brew upgrade WTFUtil
```

**Comment by BartoszCoyote** [comment]
That's right. 
Sorry to bother you.
