### ISSUE TITLE
CmdRunner problems after improvements in 0.23

### ISSUE THREAD

**Issue by kaiec** [wtfutil/wtf#732]
## What's broken?

After the improvements of #680 there are two problems:

1. The refresh of CmdRunner instances is visible when ansi color sequences are used, the module is briefly blank before the content is refreshed. 

2. The tail configuration does not work, at least with 'tail: false', the output still scrolls. I wanted to use it to get the old behaviour back.

Also the new configuration options are not in the documentation on the wtfutil.com.

**Comment by senorprogrammer** [comment]
Documentation issue handled in https://github.com/wtfutil/wtfdocs/issues/68
