### ISSUE TITLE
Module template seems quite outdated

### ISSUE THREAD

**Issue by schoentoon** [wtfutil/wtf#748]
## What's broken?
After having followed the instructions at https://wtfutil.com/configuration/generate-module/ and started working on my module, I first had to figure out that I had to add my widget to the long list at https://github.com/wtfutil/wtf/blob/master/app/widget_maker.go
After which I came to the conclusion that a newly generated module wouldn't compile. The `wtf.TextWidget` had to be changed to `view.TextWidget` for example.
Perhaps this template should be updated, maybe the generate part could output that you should add your widget to https://github.com/wtfutil/wtf/blob/master/app/widget_maker.go
Perhaps it could even be added to integration tests so this breaking in the future will sooner be realized.

**Comment by senorprogrammer** [comment]
Agreed, it's really impractical at the moment.

**Comment by 3mard** [comment]
I can take care of this :)

**Comment by senorprogrammer** [comment]
Fixed. Thanks for reporting this.
