### ISSUE TITLE
Subreddit-When top links is fewer than widget.settings.numberOfPosts

### ISSUE THREAD

**Issue by TDHTTTT** [wtfutil/wtf#753]
## What's broken?

In subreddit module, when top links from the reddit is acutally fewer than widet.settings.numberOfPosts, it will complain `panic: runtime error: slice bounds out of range`

**Comment by TDHTTTT** [comment]
I tried to fix it in #754

**Comment by senorprogrammer** [comment]
Fixed by https://github.com/wtfutil/wtf/pull/754
