### ISSUE TITLE
brew install wtfutil on Catalina: "exec format error"

### ISSUE THREAD

**Issue by macintacos** [wtfutil/wtf#765]
## What's broken?

So I don't think this is something that you can do anything about, by running `brew install wtfutil` succeeds, but executing `wtfutil` throws the error:

```
zsh: exec format error: wtfutil
```

This is on the 16" MBP, running the latest version of Catalina (10.15.1) and the latest version of Xcode

Looking at [#6539](https://github.com/Homebrew/brew/issues/6539) in Homebrew/brew, it looks like this is an issue with macOS Catalina's version of `tar`, and thus needs to be solved by Apple. If you have any other pointers to workaround (aside from installing from the release, which I have already tried and it works) I'd be happy to try them!

**Comment by senorprogrammer** [comment]
Interesting. Unfortunately I don’t have any good suggestions (downgrading the OS just for wtf seems unreasonable), and I’m not yet running Catalina myself so I can’t reproduce yet. We’ll keep this open, maybe someone else has an idea.

**Comment by Bo98** [comment]
Hi, Homebrew maintainer here.

Apologies about this - the `tar` bug is very annoying. You simply cannot create tars on Catalina at the moment and be guaranteed they're not corrupt. As far as I know, there's no workaround. Even if you recreate the tar containing the same files again, you will still consistently get a corrupt tar.

That said, we try to catch these issues during CI testing. Clearly there was a gap there for `wtfutil` which I'll try to improve for next time.

For now, I have removed the Catalina bottle. If you reinstall `wtfutil`, you will be given a copy compiled on Mojave instead.

**Comment by senorprogrammer** [comment]
@Bo98 Thanks for chiming in, providing an explanation, and hacking in a fix. That's much appreciated!

**Comment by senorprogrammer** [comment]
Keeping this open as a bug until it gets resolved upstream.

**Comment by krc** [comment]
seems like someone readded Catalina to the formula

**Comment by ianforcements** [comment]
@Bo98 it appears that as of 15th December the Catalina bottle was re-added by BrewTestBot :(

**Comment by Bo98** [comment]
Apologies - I've been away over the festive period so this went unnoticed by me.

I've pulled the bottle now.

**Comment by ianforcements** [comment]
my wtfutil is back and it's gorgeous, thank you :)
