### ISSUE TITLE
Todoist api v7 is no longer supported

### ISSUE THREAD

**Issue by tykazzz** [wtfutil/wtf#768]
https://developer.todoist.com/sync/v7/ doesnt work, because it is not supported

**Comment by tykazzz** [comment]
Of course I have my api key in config, i've deleted it

**Comment by senorprogrammer** [comment]
We're not using `v7`, we're using the v1 REST API https://github.com/wtfutil/todoist/blob/master/todoist.go#L14

What issue are you running into?

**Comment by tykazzz** [comment]
right, you just have here: https://wtfutil.com/modules/todoist/ in apikey description "Your Todoist API token." link to api v7
