### ISSUE TITLE
Add Taskwarrior integration

### ISSUE THREAD

**Issue by arshdeeptinna** [wtfutil/wtf#80]
It would be nice to have taskwarrior integration. That way i can sync tasks between my devices.

**Comment by nkoehring** [comment]
I would definitely love to see that too!

**Comment by interlock** [comment]
I'll write a simple wrapper that pulls a configured filter?

**Comment by Miterion** [comment]
@interlock I would be happy to extend that with a few keyboard shortcuts, for example to mark a task done.

**Comment by jessebett** [comment]
Would like to see taskwarrior integration as an alternative to the current todo list module.

**Comment by mrVanDalo** [comment]
I just use `cmdrunner` and `task export <filter> | jq ' .... '` which works perfectly. What else should the module do?
