### ISSUE TITLE
Twitch - Top Streams Widget

### ISSUE THREAD

**Issue by bjoernw** [wtfutil/wtf#801]
## What should it do?

Display the top streams along with the viewer count and streamer name. Open streams in browser.

I have a working version but in the spirit of talking first I wanted to check if there is interest in pulling it into master.

<img width="283" alt="Screen Shot 2019-12-25 at 5 55 26 PM" src="https://user-images.githubusercontent.com/1467156/71453361-be754200-273f-11ea-9658-0e913fd31ca4.png">

**Comment by senorprogrammer** [comment]
This looks pretty cool. Feel free to open a PR and let's bring it in.

**Comment by senorprogrammer** [comment]
Added in https://github.com/wtfutil/wtf/pull/805
