### ISSUE TITLE
Widget Event framework for notifications

### ISSUE THREAD

**Issue by bjoernw** [wtfutil/wtf#803]
Have you considered adding the ability for widgets to expose events that can be subscribed to and trigger something like desktop notifications?

For the twitch widget I'm working on it might be cool to get a notification when my favorite streamer comes online or someone big is streaming a specific game.

I'm happy to help think this through and come up with a proposal, I was just curious whether there had been some prior discussion about something like this and whether there is interest in adding that complexity.

**Comment by senorprogrammer** [comment]
Thanks for opening this issue with this suggestion. I've spent a lot of time thinking about it, and I am of two minds about it:

1. I personally don't want more notifications in my life and WTF was originally designed to serve two purposes: aggregate the important bits of data from lots of services into one info-dense pane, and keep it visible there so I didn't need notifications, I could just glance at it at-will

2. That said, I can see a path to it being useful for aggregating notifications into one source and allowing me to turn off others (currently thinking about the emails I get when a GitHub issue is opened or a PR created, for instance).

If there was a way to do this that's reliable cross-platform and simple to integrate into the modules, I would definitely be amenable to it.

**Comment by senorprogrammer** [comment]
Marking stale.
