### ISSUE TITLE
Next SpaceX Launch

### ISSUE THREAD

**Issue by bjoernw** [wtfutil/wtf#806]
## What should it do?

Display details of the next SpaceX rocket launch

<img width="664" alt="Screen Shot 2019-12-30 at 10 16 36 AM" src="https://user-images.githubusercontent.com/1467156/71594648-95f99900-2aed-11ea-8779-7e93e690ec84.png">

Layout isn't final yet...

API Source: https://docs.spacexdata.com/?version=latest#c75a20cf-50e7-4a4a-8856-ee729e0d3868

**Comment by senorprogrammer** [comment]
Very cool!

**Comment by senorprogrammer** [comment]
Added in https://github.com/wtfutil/wtf/pull/808
