### ISSUE TITLE
Random capital letters around

### ISSUE THREAD

**Issue by andersmmg** [wtfutil/wtf#811]
## What's broken?
I get random capital letters seemingly randomly strewn across the page. For a while it was capital "A", now they're capital "P". Is this supposed to be here or...
Edit: here's a screen shot, it's just a corner since I have a lot of personal info.
https://imgur.com/d2CNlT8.png

**Comment by senorprogrammer** [comment]
Could you post the OS your running this on?

**Comment by andersmmg** [comment]
OS: Manjaro 18.1.5 Juhraya
Kernel: x86_64 Linux 5.4.6-2-MANJARO

**Comment by senorprogrammer** [comment]
And no, those aren’t supposed to be there. Something is definitely glitched.

**Comment by Seanstoppable** [comment]
@andersmmg can you also share the value of $TERM?

**Comment by BonoVanderpoorten** [comment]
Hey,
Having the same issue, I'm on WSL in the new Windows Terminal though.
I suffer the letter P and they seem to pop up over time, zooming / tabbing may make them appear more frequently. 

Img:
https://i.imgur.com/6alDGR2.png

**Comment by willjohnson** [comment]
I am having the filepath of my textfile widget randomly written to my screen. Possibly related?

**Comment by GideonWolfe** [comment]
+1, Also experiencing this issue on `Arch Linux 5.6.2` with `urxvt`. Random `A`s and `P`s being dropped all over the terminal.

**Comment by jonhadfield** [comment]
Appears to be a bug in the digitalclock module.  
I've submitted a fix in https://github.com/wtfutil/wtf/pull/883.

**Comment by senorprogrammer** [comment]
Fixed by https://github.com/wtfutil/wtf/pull/883
