### ISSUE TITLE
Build via Dockerfile broken on master branch

### ISSUE THREAD

**Issue by firecat53** [wtfutil/wtf#816]
## What's broken?
As of 2020-01-12, building via Dockerfile is broken on master branch with the following error:

    Step 9/10 : RUN make build                                                                                                              
     ---> Running in cfb849b758a0                                                                                                           
    go build -o bin/wtfutil -mod=vendor                                                                                                     
    build github.com/wtfutil/wtf: cannot load github.com/microsoft/azure-devops-go-api/azuredevops: open /go/src/github.com/wtfutil/wtf/vend
    or/github.com/microsoft/azure-devops-go-api/azuredevops: no such file or directory                                                      
    make: *** [Makefile:33: build] Error 1 

Building the latest release v0.25.0 works correctly.

Thanks!

**Comment by senorprogrammer** [comment]
Running `make docker-build` should be working again with 0.27.0.
