### ISSUE TITLE
Docker does not run: ERROR Could not create the '~/.config/' directory

### ISSUE THREAD

**Issue by Hubbitus** [wtfutil/wtf#821]
```
$ ls configs/
sample_config.yml
$ docker run -v $(pwd)/configs:/configs -it wtfutil/wtf wtfutil --config=/configs/sample_config.yml

ERROR Could not create the '~/.config/' directory.

Error: mkdir : no such file or directory
```

**Comment by Seanstoppable** [comment]
This seems to be due to some old golang bug that seems to be fixed, in that it can't find a user and then bombs out (on linux).

I currently worked around this by setting `-e USER=wtfutil`, and am debugging some more to understand before comitting a better fix.

**Comment by senorprogrammer** [comment]
Is this still an issue, given the docker improvements that were added in v0.26.0?

**Comment by senorprogrammer** [comment]
Closing this due to lack of reproducibility and response.

**Comment by Hubbitus** [comment]
Is there commit for better fix?

**Comment by Hubbitus** [comment]
@senorprogrammer, what responce are you waiting?

**Comment by senorprogrammer** [comment]
I personally don't use docker to run WTF so I'm waiting for someone who can a) reproduce, b) inform whether or not @Seanstoppable's suggested fix, mentioned above, works, or c) provide a solution for it.
