### ISSUE TITLE
Issue #781 still not resolved, todoist project id can't be greater than 2147483647

### ISSUE THREAD

**Issue by lakomyt** [wtfutil/wtf#835]
When running wtfutil with todoist project id greater than 2147483647 it doesn't launch.
`Error: Unsupported map value`
Raspbian buster 10, armv7l

**Comment by senorprogrammer** [comment]
This would be a bug in https://github.com/wtfutil/todoist

**Comment by senorprogrammer** [comment]
(Keeping this open here because I don't seem to be able to transfer it to that repo)
