### ISSUE TITLE
Disable Docker Module blinking text

### ISSUE THREAD

**Issue by kyleknighted** [wtfutil/wtf#847]
## How can we help?

The heading `system` and `containers` within the Docker module are blinking.
This is distracting as I would only want something to blink if it's an error or notification of some sort. 

I do not see any settings for disabling this blink effect and was curious if there is something I can do to remove the blinking?

Thanks!

**Comment by senorprogrammer** [comment]
Interesting. I doubt that’s intentional. Could to post your OS and $TERM value?

**Comment by kyleknighted** [comment]
**OS:** Mac OS X v10.14.6
**$TERM:** `xterm-256color`

**Comment by senorprogrammer** [comment]
Thanks. I’ll try and reproduce
