### ISSUE TITLE
Unable to install from source due to k8s.io/client-go not building

### ISSUE THREAD

**Issue by dietrichm** [wtfutil/wtf#851]
Hi

I'm installing WTF from source using the instructions available in `README.md`. Unfortunately I can't get past the build step for `k8s.io/client-go`:

```
# k8s.io/client-go/rest
go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
        have (*versioned.Decoder)
        want (watch.Decoder, watch.Reporter)
```

I'm using Go version 1.14.

Looking for similar issues in other projects, it seems the versions for `k8s.io/client-go` have to be fixed to a compatible version.

## How can we help?

Being a Go newcomer I'm unsure if this is something I can remedy myself, as it seems this should be fixed in `go.mod` in the package.

Thanks

**Comment by senorprogrammer** [comment]
Thanks, I'll take a look

**Comment by senorprogrammer** [comment]
I don't believe this is happening anymore.
