### ISSUE TITLE
Exchangerates: alignment and formatting

### ISSUE THREAD

**Issue by OJFord** [wtfutil/wtf#897]
## What should it do?
Currently the alignment gets out of whack if you have exchange rates with varying numbers of digits to the left of the decimal point:
```
│1 GBP = 1.216841 USD    │
│1 GBP = 92.393901 INR   │
```

It'd be nice to have an option to specify number of significant figures, so that `3` for example would give GBP/USD `1.22`, and GBP/INR `92.4`.

With that, an `align: centre` option could make sense to put the padding evenly on the left/right of the data.

Finally, what I'd ideally like is an option to specify formatting, specifically for `GBP/USD  1.216841` rather than the more verbose description at the moment, but it could be described using something general like:
```
format: '%(from)/%(to)  %(rate)'
```

to make it more configurable for different preferences. In combination with a significant figure clipping, that would actually take care of my alignment request too (with manual spacing in the format string to match up with the column width).

**Comment by senorprogrammer** [comment]
This PR addresses the first alignment issues describes in this issue: https://github.com/wtfutil/wtf/pull/939

I like the idea of having either a simplified display or a user-specified display format. That might come in an additional PR.
