### ISSUE TITLE
Reset scroll position on unfocus

### ISSUE THREAD

**Issue by OJFord** [wtfutil/wtf#899]
## What should it do?
If you scroll down in a feed, for example, so that only entries 15-30 are visible, it would be nice if on changing or removing all focus, it reverted to displaying entries 1-15.

**Comment by senorprogrammer** [comment]
What tangible benefit would this change provide? From the sounds of it, that would be unlike scrolling behaviour in any other viewport (OS window, browser, etc.).

**Comment by OJFord** [comment]
In `feedreader` or `hackernews` modules for example, one might scroll down having read or been uninterested in the higher ranked entries, defocus to do something else, and in the mean time the feed is refreshing, but the view into it is a sort of arbitrarily positioned window.

> that would be unlike scrolling behaviour in any other viewport (OS window, browser, etc.)

That's true, but on refresh a browser, at least, does go back to the top of the page.

(Or, more precisely, the anchor in the URL, which I'd say is analogous to configuring a most-recent items feed, or HN top.)

**Comment by senorprogrammer** [comment]
I appreciate the use-case you're describing, but I think this would be very unpredictable for all other users. I personally would find it very frustrating to tab from a view I was reading to another, back again, and have them both reset their position.

```
That's true, but on refresh a browser, at least, does go back to the top of the page.
```
This is not the behaviour any of the browsers I use exhibit. All of them, on reload, preserve the scroll position.

I would not accept a PR for this change.
