### ISSUE TITLE
Scrolling to bottom overshoots

### ISSUE THREAD

**Issue by OJFord** [wtfutil/wtf#900]
## What's broken?
If you navigate up one from the top, or all the way down, in a focused module like a feed for example, then the pane overshoots by one line leaving a blank at the bottom.

This happens even if there is nothing to scroll to, and all are visible without focusing and navigation up/all the way down.

**Comment by senorprogrammer** [comment]
Fixed by https://github.com/wtfutil/wtf/pull/977
