### ISSUE TITLE
To add support for stock values

### ISSUE THREAD

**Issue by viggy28** [wtfutil/wtf#930]
Have been playing with wtfutil recently and really impressed. Thanks, folks. One thing surprised is there is no module for equities. I am not sure there were any past conversations around it. (At least my search issues didn't bring any)

## What should it do?
It should show the stock values of the company that you would like to see. Can support any of the providers who have a Go package. https://rapidapi.com/blog/best-stock-api/ or alpaca which provides https://github.com/alpacahq/alpaca-trade-api-go/

**Comment by applegreengrape** [comment]
I'd like to give this a go :). setting up the alpaca module for the stock view

**Comment by senorprogrammer** [comment]
Go for it 👍

**Comment by applegreengrape** [comment]
@viggy28 , @senorprogrammer I cannot have access to alpaca as I am not a US resident. Did a little bit of research on this subject, found a good API - https://finnhub.io/. The data seems to be decent enough. Is it good enough?

<img width="448" alt="Screenshot 2020-10-19 at 20 50 30" src="https://user-images.githubusercontent.com/17727004/96505068-864e6b00-124d-11eb-87d5-bf257ee8ae43.png">

**Comment by senorprogrammer** [comment]
Looks great to me.

**Comment by senorprogrammer** [comment]
Added with this PR: https://github.com/wtfutil/wtf/pull/1004

Note that WTF can easily support multiple stock providers so if someone wants to create one for Alpaca as well, please do.
