### ISSUE TITLE
Jira Module - Basic auth for self hosted jira server

### ISSUE THREAD

**Issue by stillru** [wtfutil/wtf#941]
## What should it do?
To work with REST jira API in selfhosted servers we need support basic authentication

**Comment by arashous** [comment]
At one point just putting the password into the apiKey property was working with onprem Jira. But that doesn't seem to be the case anymore. Not sure if the change in behavior is due to newer Jira, api or changes in the wtfutil jira module.

**Comment by arashous** [comment]
So I take back what I said, it does work. Put password as apiKey value. And put username as email value. The module auths with email + apiKey, which maps to username + password when using basic auth.

If the JQL or Project value is incorrect it still seems to throw a 400, which looks like auth issues. 

`
    jira:
      apiKey: "MY_JIRA_PASSWORD"
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      domain: "https://jira.trifacta.net"
      email: "MY_JIRA_USERNAME (NOT EMAIL)"
      enabled: true
      #jql: 'issuetype in (standardIssueTypes(), subTaskIssueTypes()) AND status in ("In Progress", Selected) AND resolution = Unresolved AND assignee in (currentUser()) order by updated DESC'
      position:
        top: 2
        left: 1
        height: 1
        width: 3
      project: "PROJECT_KEY"
      refreshInterval: 100
      username: "MY_JIRA_USERNAME"
      verifyServerCertificate: true 
      title: "Jira - In Progress/On Deck"     
`

**Comment by stillru** [comment]
Thanx. It work like you sad. But now - when i change my configuration - i get `404` error...

jira `v8.5.1#805001-sha1:c5b54a7`
