### ISSUE TITLE
Twitter Lists

### ISSUE THREAD

**Issue by michaelMinar** [wtfutil/wtf#956]
## What should it do?
Would it be generally desirable to have an option in the Twitter module for pulling recent tweets from a public list, as an alternative to pulling from a single user?

**Comment by tombiju** [comment]
Hi, I wanted to give a shot at this, is there more details as to what this entails? Are we allowing the user to specify a list of other users to get tweets from?

**Comment by senorprogrammer** [comment]
Right now the Twitter module allows the user to specify users only via the `screenNames` config option. I suspect they're thinking of something like a `lists` config option that would interact with this API https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/create-manage-lists/overview
