### ISSUE TITLE
Add basic authentication support for RSS feed reader

### ISSUE THREAD

**Issue by atgreen** [wtfutil/wtf#957]
## What should it do?
From what I can tell, the feed parser can only read public feeds.  Please consider adding support basic authentication support for private feeds.

**Comment by FliegendeWurst** [comment]
It is already possible to specify the username and password like this: `https://username:password@example.com/feed.rss`

**Comment by senorprogrammer** [comment]
@atgreen Does this solution work for you?

**Comment by ResamVi** [comment]
Hi, I'm looking around for hacktoberfest.
Adding username and password to the URL does do the trick, I've just tried it in a test.

Would it be useful if username+password attributes were added to the module?
That would be the solution a single private feed (multiple feeds with different credentials would require a bit more)

**Comment by senorprogrammer** [comment]
I think extending the module config to support those values, and being able to use them if they're both supplied in the feed URL or in the configuration would be a great improvement.

**Comment by senorprogrammer** [comment]
For that, might want to change the config format from a list to a map. We'd still need to support both for backwards compatibility (we do this in a number of places, try parsing one type first, if that fails, fall back to the default type and try again).
