### ISSUE TITLE
Crashing with certain RSS feeds

### ISSUE THREAD

**Issue by SergeantBiggs** [wtfutil/wtf#958]
## What's broken?
When using certain RSS feeds, the program crashes. I went back and tested, and it crashes from version v0.30.0 and upward.

Example of RSS feed that makes the program crash:
https://github.com/openwrt/openwrt/tags.atom

I'm guessing it was introduced with https://github.com/wtfutil/wtf/pull/886

**Comment by senorprogrammer** [comment]
Fixed by https://github.com/wtfutil/wtf/pull/977
