### ISSUE TITLE
GitHub Module: cannot disable showMyPullRequests

### ISSUE THREAD

**Issue by alexfornuto** [wtfutil/wtf#959]
## What's broken?
in the module `github`, there's a [documented](https://wtfutil.com/modules/github/) feature to disable the "My Pull Requests" section. Even when set to false, the section remains:

![image](https://user-images.githubusercontent.com/2349184/91077343-855edb80-e606-11ea-8b4d-6718aab13c9f.png)

The only workaround I can think of is to remove `username` and get an empty list.

**Comment by rossdeane** [comment]
@alexfornuto can you share the rest of your config for this module? 
Setting to false seems to hide it for me at the moment.

**Comment by senorprogrammer** [comment]
I'm not able to reproduce this either (see attached screenshot). @alexfornuto Which version are you running (`wtfutil --version`)? Could this have been against a version that didn't support that config yet?

<img width="548" alt="Screen Shot 2020-10-02 at 4 27 50 AM" src="https://user-images.githubusercontent.com/6413/94918567-ae755600-0467-11eb-81e9-0a2401d8b552.png">

**Comment by alexfornuto** [comment]
Yup, I didn't realize my version was that old. Sorry for the false alarm.
