### ISSUE TITLE
Configure amount of padding inside modules

### ISSUE THREAD

**Issue by mynameislouie** [wtfutil/wtf#964]
Is it possible to add the ability to change the interior padding of modules? With visible borders the text can sometimes look a little close to the edges. Maybe even text alignment? For example when using cmdrunner to output the result of an applescript it would be nice to be able to easily align the output.

**Comment by senorprogrammer** [comment]
Right now there's no way to define text formatting for most modules. They have it hard-coded into the individual modules themselves, which is something that should be changed for flexibility, but that's not on the radar at the moment.

For formatting CmdRunner content, you could work around this by formatting the output within the script itself, before passing it back to WTF for display.

**Comment by huyz** [comment]
A padding option would be nice
