### ISSUE TITLE
[RFC] Widget for UptimeRobot

### ISSUE THREAD

**Issue by franga2000** [wtfutil/wtf#979]
Hi! I'd like to add a module that I (and hopefully others) would find very useful and I'm looking for some feedback before I send a PR.

## What should it do?

Display a list of uptime monitors from the [Uptime Robot](https://uptimerobot.com) website/server monitoring service, with their state, uptime percentage and possibly some other useful bits of info regarding downtime. 

## Design

I've implemented most of the drawing code, so I can show you roughly how it would look (I haven't quite gotten Unicode icons to work yet). 

![image](https://user-images.githubusercontent.com/3891092/94992373-dfe64280-0589-11eb-8312-a50eae42f07f.png)

## Implementation

The main thing I'd like to ask regarding this is if there is a general rule in this project on whether to prefer using existing libraries or direct communication with APIs.  
All this widget requires is a single JSON API endpoint so it seems a bit overkill to drag yet another dependency like [bitfield/uptimerobot](https://github.com/bitfield/uptimerobot) into the project, but on the other hand, I know some maintainers prefer external libraries wherever possible so they can just pull in updates if something breaks, which is why I ask.

Any other ideas/comments regarding features/design/anything are of course welcome!

**Comment by senorprogrammer** [comment]
Sounds great! As for lib vs. API, up to you. Whichever you prefer.

**Comment by senorprogrammer** [comment]
Added in https://github.com/wtfutil/wtf/pull/983
